import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

const translationDictionary = {
  hi: {
    // Nav links & common
    "Home": "मुख्य पृष्ठ",
    "Products": "उत्पाद",
    "Services": "सेवाएं",
    "About Us": "हमारे बारे में",
    "FAQ": "अक्सर पूछे जाने वाले प्रश्न (FAQ)",
    "Social Media": "सोशल मीडिया",
    "Follow Us": "हमें फॉलो करें",
    "Contact Us": "संपर्क करें",
    "Connect Now!": "अभी जुड़ें!",
    "Explore Products": "उत्पाद देखें",
    "Subscribe on WhatsApp →": "व्हाट्सएप पर सब्सक्राइब करें →",
    "Order on WhatsApp": "व्हाट्सएप पर ऑर्डर करें",
    "Enquire on WhatsApp →": "व्हाट्सएप पर पूछताछ करें →",
    "Enquire on WhatsApp &rarr;": "व्हाट्सएप पर पूछताछ करें →",
    "In Stock": "स्टॉक में है",
    "Out of Stock": "आउट ऑफ स्टॉक",
    "Active": "सक्रिय",
    "Inactive": "निष्क्रिय",
    "Type of Making": "बनाने की विधि",
    "Available": "उपलब्धता",
    "Suitable for Fast": "उपवास के लिए उपयुक्त",
    "Stock Status": "स्टॉक की स्थिति",
    "Product Specifications": "उत्पाद विनिर्देश",
    "Subscription Packages": "सदस्यता पैकेज",
    "1 Day Plan": "1 दिन का प्लान",
    "6 Days Plan": "6 दिन का प्लान",
    "25 Days Plan": "25 दिन का प्लान",
    "Trust Builder": "भरोसा निर्माता",
    "Most Popular": "सबसे लोकप्रिय",
    "Best Seller": "बेस्ट सेलर",
    "Cleanse. Refresh. Rejuvenate.": "स्वच्छ। ताज़ा। कायाकल्प।",
    "Health & Nutritional Benefits": "स्वास्थ्य और पोषण संबंधी लाभ",
    "Precautions (Not suitable for / Who should not consume)": "सावधानियां (किसके लिए उपयुक्त नहीं है / किसे सेवन नहीं करना चाहिए)",
    "Available Varieties": "उपलब्ध किस्में",
    "You May Also Like": "आपको यह भी पसंद आ सकता है",
    "Delivered Fresh": "ताजा डिलीवरी",
    "At your doorstep": "आपके दरवाजे पर",
    "Secure Payment": "सुरक्षित भुगतान",
    "100% safe & secure": "100% सुरक्षित",
    "Subscription Plans": "सदस्यता योजनाएं",
    "Save more with plans": "प्लान के साथ अधिक बचत करें",
    "100% Satisfaction": "100% संतुष्टि",
    "We care for you": "हम आपकी परवाह करते हैं",

    // Hero
    "YOGYAHAR — Follow Your Diet With Us!": "योग्याहार — हमारे साथ अपने आहार का पालन करें!",
    "Fresh. Natural. Hygienic.": "ताजा। प्राकृतिक। स्वच्छ।",
    "Tasty. Authentic.": "स्वादिष्ट। प्रामाणिक।",
    "No preservatives, no chemicals, no artificial colors, no added sugar, only Pure Products.": "कोई परिरक्षक नहीं, कोई रसायन नहीं, कोई कृत्रिम रंग नहीं, कोई अतिरिक्त चीनी नहीं, केवल शुद्ध उत्पाद।",
    "Fresh & Natural": "ताजा और प्राकृतिक",
    "No Chemicals": "कोई रसायन नहीं",
    "No Preservatives": "कोई परिरक्षक नहीं",
    "No Added Sugar": "कोई अतिरिक्त चीनी नहीं",
    "Doorstep Delivery": "घर तक डिलीवरी",
    "Across Nashik": "पूरे नासिक में",
    "100% Vegetarian": "100% शाकाहारी",
    "Made to Order": "ऑर्डर पर निर्मित",

    // About Us (Home)
    "Good Health Starts with the Right Choice!": "अच्छा स्वास्थ्य सही चुनाव से शुरू होता है!",
    "Since 2018, YOGYAHAR makes fresh, natural, hygienic, tasty, authentic diet food — protein-packed salads, cold-pressed juices, and ready-to-eat/ready-to-cook meal kits. We believe in selling Taste, Time, Knowledge, Variety, and Consistency.": "2018 से, योग्याहार ताजा, प्राकृतिक, स्वच्छ, स्वादिष्ट, प्रामाणिक आहार भोजन बनाता है - प्रोटीन से भरपूर सलाद, कोल्ड-प्रेस्ड जूस और खाने के लिए तैयार/पकाने के लिए तैयार भोजन किट। हम स्वाद, समय, ज्ञान, विविधता और निरंतरता बेचने में विश्वास करते हैं।",
    "\"We Don't Just Serve Food, We Serve a Healthier You!\"": "\"हम केवल भोजन नहीं परोसते, हम आपके बेहतर स्वास्थ्य की सेवा करते हैं!\"",
    "To make available Fresh, Natural, Hygienic, Tasty, and Authentic diet food anytime at possible location.": "ताजा, प्राकृतिक, स्वच्छ, स्वादिष्ट और प्रामाणिक आहार भोजन किसी भी समय संभावित स्थान पर उपलब्ध कराना।",
    "To create a healthy nation by serving diet food at an affordable cost with a sustainable business model.": "एक टिकाऊ व्यावसायिक मॉडल के साथ किफायती लागत पर आहार भोजन परोसकर एक स्वस्थ राष्ट्र का निर्माण करना।",

    // Ayurveda Quote
    "Charak Samhita · Sutra 30.26": "चरक संहिता · सूत्र 30.26",
    "स्वस्थस्य स्वास्थ्य रक्षणं । आतुरस्य विकार प्रशमनं च ॥": "स्वस्थस्य स्वास्थ्य रक्षणं । आतुरस्य विकार प्रशमनं च ॥",
    "आयुर्वेद का मुख्य उद्देश्य स्वस्थ लोगों के स्वास्थ्य को बनाए रखना और बीमार लोगों की बीमारी को ठीक करना है।": "आयुर्वेद का मुख्य उद्देश्य स्वस्थ लोगों के स्वास्थ्य को बनाए रखना और बीमार लोगों की बीमारी को ठीक करना है।",
    "\"The main purpose of Ayurveda is to maintain the health of the healthy and to cure the disease of the ill.\"": "\"आयुर्वेद का मुख्य उद्देश्य स्वस्थ व्यक्ति के स्वास्थ्य की रक्षा करना और रोगी के रोग को शांत करना है।\"",

    // Stats
    "Registered Happy Customers": "पंजीकृत खुशहाल ग्राहक",
    "Salads and Juices": "सलाद और जूस",
    "Km of Daily Doorstep Delivery": "दैनिक होम डिलीवरी (किमी)",
    "Direct-Indirect Employment": "प्रत्यक्ष-अप्रत्यक्ष रोजगार",

    // How It Works
    "How It Works": "यह कैसे काम करता है",
    "Clean Eating, Made Simple": "स्वच्छ खान-पान, हुआ आसान",
    "We make healthy living easy with a simple and efficient process.": "हम एक सरल और कुशल प्रक्रिया के साथ स्वस्थ जीवन को आसान बनाते हैं।",
    "Choose Your Plan": "अपना प्लान चुनें",
    "Trial, 6-day or 25-day subscription": "ट्रायल, 6-दिन या 25-दिन की सदस्यता",
    "Order on WhatsApp": "व्हाट्सएप पर ऑर्डर करें",
    "Message us to place or customize your order": "ऑर्डर करने या कस्टमाइज़ करने के लिए हमें मैसेज करें",
    "We Prepare Fresh": "हम ताजा तैयार करते हैं",
    "Made to order daily, no preservatives": "दैनिक ऑर्डर पर निर्मित, कोई परिरक्षक नहीं",
    "6–8 AM and 6–8 PM across Nashik": "पूरे नासिक में सुबह 6-8 और शाम 6-8 बजे",
    "Eat Healthy": "स्वस्थ खाएं",
    "Enjoy fresh, vegetarian, guilt-free food": "ताजा, शाकाहारी, बिना किसी अपराधबोध के भोजन का आनंद लें",

    // Plans
    "Subscription Programs": "सदस्यता कार्यक्रम",
    "Follow Your Diet With Us": "हमारे साथ अपने आहार का पालन करें",
    "We offer 6-day and 25-day subscriptions, plus a single serving trial so you can try before you subscribe.": "हम 6-दिन और 25-दिन की सदस्यता प्रदान करते हैं, साथ ही एक सिंगल ट्रायल भी ताकि आप सदस्यता लेने से पहले देख सकें।",
    "Choose from a 1-day trust builder, 6-day wellness plan, or our full 25-day transformation subscription. Fresh deliveries every morning and evening.": "1-दिन के ट्रस्ट बिल्डर, 6-दिन के वेलनेस प्लान, या हमारे पूरे 25-दिन के ट्रांसफॉर्मेशन सब्सक्रिप्शन में से चुनें। हर सुबह और शाम ताजा डिलीवरी।",
    "Morning Slot": "सुबह का समय",
    "Evening Slot": "शाम का समय",
    "Morning Slot: ": "सुबह का समय: ",
    "Evening Slot: ": "शाम का समय: ",
    "Single Serving Trial": "सिंगल सर्विंग ट्रायल",
    "Try before you subscribe": "सदस्यता लेने से पहले आज़माएं",
    "No commitment": "कोई प्रतिबद्धता नहीं",
    "One-time order": "एक बार का ऑर्डर",
    "Any juice or salad": "कोई भी जूस या सलाद",
    "Order via WhatsApp": "व्हाट्सएप के माध्यम से ऑर्डर करें",
    "6 Days Subscription": "6 दिनों की सदस्यता",
    "A week of goodness": "एक सप्ताह की अच्छाई",
    "Great for beginners": "शुरुआती लोगों के लिए बढ़िया",
    "Daily fresh delivery": "दैनिक ताजा डिलीवरी",
    "Choice of juices/salads": "जूस/सलाद का विकल्प",
    "Doorstep delivery": "घर तक डिलीवरी",
    "25 Days Subscription": "25 दिनों की सदस्यता",
    "Full month transformation": "पूरे महीने का बदलाव",
    "Best value": "सबसे अच्छा मूल्य",
    "Customizable diet plan": "कस्टमाइज़ करने योग्य डाइट प्लान",
    "Priority doorstep delivery": "प्राथमिकता होम डिलीवरी",
    "1 Day": "1 दिन",
    "6 Days": "6 दिन",
    "25 Days": "25 दिन",
    "Single day serving": "एक दिन की सर्विंग",
    "Juice or Salad of your choice": "आपकी पसंद का जूस या सलाद",
    "200ml / 300ml / 500ml (Juice)": "200 मिली / 300 मिली / 500 मिली (जूस)",
    "200gm / 450gm (Salad)": "200 ग्राम / 450 ग्राम (सलाद)",
    "Morning (6–9 am) or Evening (5–7 pm)": "सुबह (6–9 बजे) या शाम (5–7 बजे)",
    "6 consecutive days": "लगातार 6 दिन",
    "Juice + Salad combos available": "जूस + सलाद कॉम्बो उपलब्ध",
    "25 days of daily wellness": "25 दिनों की दैनिक भलाई",
    "Single or combo products": "सिंगल या कॉम्बो उत्पाद",

    // Products
    "All subscription-based products are available in Weekly and Monthly packages.": "सभी सदस्यता-आधारित उत्पाद साप्ताहिक और मासिक पैकेजों में उपलब्ध हैं।",
    "Carrot Juice": "गाजर का जूस",
    "Amla Juice": "आंवला जूस",
    "Green Juice": "ग्रीन जूस",
    "Mix Juice": "मिक्स जूस",
    "Watermelon Juice": "तरबूज का जूस",
    "Sugarcane Juice": "गन्ने का जूस",
    "Beetroot Juice": "चुकंदर का जूस",
    "Combination Juice": "कॉम्बिनेशन जूस",
    "Red Juice": "रेड जूस",
    "Salad Meal": "सलाद भोजन",
    "Fruit Cuts": "कटे हुए फल",
    "Salad Bowl": "सलाद बाउल",
    "Sprout Salad": "अंकुरित सलाद",
    "Super Laddu": "सुपर लड्डू",
    "Cold Pressed Oil": "कोल्ड प्रेस्ड ऑयल",
    "Super Dry Fruits Laddu": "सुपर ड्राई फ्रूट्स लड्डू",

    // FAQ
    "Frequently Asked Questions": "अक्सर पूछे जाने वाले प्रश्न",
    "Have more questions? Ask AI": "और सवाल हैं? एआई से पूछें",
    "What is YOGYAHAR and what do you offer?": "योग्याहार क्या है और आप क्या प्रदान करते हैं?",
    "YOGYAHAR is Nashik's trusted diet food brand offering fresh, natural, hygienic, tasty, and authentic ready-to-eat meals, salads, and juices.": "योग्याहार नासिक का विश्वसनीय डाइट फूड ब्रांड है जो ताजा, प्राकृतिक, स्वच्छ, स्वादिष्ट और प्रामाणिक रेडी-टू-ईट भोजन, सलाद और जूस प्रदान करता है।",
    "Are your meals and juices really fresh and preservative-free?": "क्या आपके भोजन और जूस वास्तव में ताजे और परिरक्षक-मुक्त हैं?",
    "Absolutely, every made-to-order YOGYAHAR meal and juice is prepared fresh daily using natural ingredients. No preservatives, no artificial colors, and no added sugar.": "बिल्कुल, हर योग्याहार भोजन और जूस प्राकृतिक सामग्री का उपयोग करके दैनिक रूप से ताजा तैयार किया जाता है। कोई परिरक्षक नहीं, कोई कृत्रिम रंग नहीं, और कोई अतिरिक्त चीनी नहीं।",
    "What types of subscriptions do you offer?": "आप किस प्रकार की सदस्यताएँ प्रदान करते हैं?",
    "We offer 6 days and 25 days subscriptions. You can also order a single serving to try before starting your subscription.": "हम 6 दिन और 25 दिन की सदस्यता प्रदान करते हैं। आप अपनी सदस्यता शुरू करने से पहले आज़माने के लिए एक सिंगल सर्विंग भी ऑर्डर कर सकते हैं।",
    "What are your delivery hours?": "आपके डिलीवरी के घंटे क्या हैं?",
    "We deliver daily from 6:00 AM to 8:00 AM and 6 PM to 8 PM across Nashik City.": "हम पूरे नासिक शहर में रोजाना सुबह 6:00 से 8:00 बजे और शाम 6 से 8 बजे तक डिलीवरी करते हैं।",
    "What payment methods do you accept?": "आप कौन सी भुगतान विधियां स्वीकार करते हैं?",
    "We accept UPI, Cash, and secure online payment links.": "हम यूपीआई (UPI), नकद और सुरक्षित ऑनलाइन भुगतान लिंक स्वीकार करते हैं।",
    "Do you provide non-veg salad?": "क्या आप नॉन-वेज सलाद प्रदान करते हैं?",
    "No, YOGYAHAR purely focuses on vegetarian diet food.": "नहीं, योग्याहार पूरी तरह से शाकाहारी डाइट फूड पर केंद्रित है।",
    "Can I customize my meals?": "क्या मैं अपने भोजन को कस्टमाइज़ कर सकता हूँ?",
    "Our meals are mainly pre-designed, but custom plans are possible via a WhatsApp request to +91 7499643234.": "हमारे भोजन मुख्य रूप से पूर्व-डिज़ाइन किए गए हैं, लेकिन +91 7499643234 पर व्हाट्सएप अनुरोध के माध्यम से कस्टम प्लान संभव हैं।",

    // Newsletter
    "Never miss a single news": "एक भी खबर न चूकें",
    "Stay informed with updates on our products and services. Stay connected and follow your diet with us!": "हमारे उत्पादों और सेवाओं के अपडेट से सूचित रहें। जुड़े रहें और हमारे साथ अपने आहार का पालन करें!",
    "📩 Stay Updated with YOGYAHAR": "📩 योग्याहार के साथ अपडेट रहें",
    "Subscribe to our newsletter for the latest updates, offers & health tips.": "नवीनतम अपडेट, ऑफ़र और स्वास्थ्य युक्तियों के लिए हमारे न्यूज़लेटर की सदस्यता लें।",
    "Enter your email address": "अपना ईमेल पता दर्ज करें",
    "Subscribe": "सदस्यता लें",

    // Footer
    "Quick Links": "त्वरित लिंक",
    "Nashik's trusted diet food brand since 2018. Follow Your Diet With Us — fresh, natural, hygienic, vegetarian meals, salads and juices, delivered to your doorstep.": "2018 से नासिक का विश्वसनीय डाइट फूड ब्रांड। हमारे साथ अपने आहार का पालन करें - ताजा, प्राकृतिक, स्वच्छ, शाकाहारी भोजन, सलाद और जूस, आपके दरवाजे पर डिलीवर किए जाते हैं।",
    "🕐 6–8 AM & 6–8 PM daily": "🕐 रोजाना सुबह 6–8 और शाम 6–8 बजे",
    "📍 Nashik, Maharashtra, India": "📍 नासिक, महाराष्ट्र, भारत",
    "© 2025 YOGYAHAR All Rights Reserved.": "© 2025 योग्याहार सर्वाधिकार सुरक्षित।",
    "Follow Your Diet With Us!": "हमारे साथ अपने आहार का पालन करें!",

    // Standalone: Contact Us
    "We'd Love to Hear From You!": "हमें आपसे सुनना अच्छा लगेगा!",
    "Have a question, feedback, or just want to say hello? We're here for you. Reach out to us and we'll get back to you as soon as possible.": "कोई सवाल, प्रतिक्रिया है, या सिर्फ नमस्ते कहना चाहते हैं? हम आपके लिए यहां हैं। हमसे संपर्क करें और हम जल्द से जल्द आपसे संपर्क करेंगे।",
    "Our Location": "हमारा स्थान",
    "Call Us": "हमें कॉल करें",
    "Email Us": "हमें ईमेल करें",
    "Working Hours": "कामकाज के घंटे",
    "Send Us a Message": "हमें एक संदेश भेजें",
    "We'll respond to your inquiry as soon as possible.": "हम जल्द से जल्द आपकी पूछताछ का जवाब देंगे।",
    "Your Name": "आपका नाम",
    "Email Address": "ईमेल पता",
    "Phone Number": "फ़ोन नंबर",
    "Subject": "विषय",
    "Your Message": "आपका संदेश",
    "Send Message": "संदेश भेजें",
    "Thank you!": "धन्यवाद!",
    "Your message has been sent successfully.": "आपका संदेश सफलतापूर्वक भेज दिया गया है।",

    // Standalone: About Us page
    "Providing Wholesome Diet Nutrition Since 2018": "2018 से संपूर्ण आहार पोषण प्रदान कर रहे हैं",
    "Welcome to our standalone About page! We make fresh, natural, hygienic, tasty, authentic diet food. We believe in selling Taste, Time, Knowledge, Variety, and Consistency.": "हमारे standalone अबाउट पेज पर आपका स्वागत है! हम ताजा, प्राकृतिक, स्वच्छ, स्वादिष्ट, प्रामाणिक आहार भोजन बनाते हैं। हम स्वाद, समय, ज्ञान, विविधता और निरंतरता बेचने में विश्वास करते हैं।",
    "\"Nourishing your body with local healthy products, delivered fresh daily.\"": "\"स्थानीय स्वस्थ उत्पादों के साथ आपके शरीर का पोषण, दैनिक रूप से ताजा डिलीवर किया जाता है।\"",
    "Ready To Start Your": "शुरू करने के लिए तैयार हैं अपनी",
    "Health Journey?": "स्वास्थ्य यात्रा?",
    "Join thousands of happy customers who trust YOGYAHAR to fuel their body and nourish their life.": "उन हजारों खुशहाल ग्राहकों में शामिल हों जो अपने शरीर को ईंधन देने और अपने जीवन को पोषण देने के लिए योग्याहार पर भरोसा करते हैं।",

    // Standalone: Services
    "Tailored Plans for Your Health Goals": "आपके स्वास्थ्य लक्ष्यों के लिए विशेष योजनाएं",
    "We deliver delicious, portion-controlled diet food across Nashik to fit your lifestyle.": "हम आपकी जीवनशैली के अनुकूल नासिक में स्वादिष्ट, नियंत्रित मात्रा में आहार भोजन वितरित करते हैं।",
    "Office Professionals": "कार्यालय पेशेवर",
    "Gym & Fitness Lovers": "जिम और फिटनेस प्रेमी",
    "Weight Loss Followers": "वजन घटाने वाले",
    "Family & Seniors": "परिवार और बुजुर्ग",
    "Fuel your productive workdays with Yogyahar's desk-friendly meal plans. Convenient, nourishing, and delivered fresh to help corporate professionals maintain peak focus without the midday slump.": "योग्याहार के डेस्क-अनुकूल भोजन योजनाओं के साथ अपने उत्पादक कार्यदिवसों को ऊर्जा दें। सुविधाजनक, पौष्टिक, और कॉर्पोरेट पेशेवरों को दोपहर की सुस्ती के बिना ध्यान बनाए रखने में मदद करने के लिए ताजा वितरित किया जाता है।",
    "Support your active lifestyle and workout recovery with Yogyahar's high-protein bowls and clean energy snacks. Carefully portioned and nutrient-dense fuel designed specifically for fitness enthusiasts.": "योग्याहार के उच्च-प्रोटीन बाउल और स्वच्छ ऊर्जा स्नैक्स के साथ अपनी सक्रिय जीवनशैली और कसरत के बाद रिकवरी का समर्थन करें। विशेष रूप से फिटनेस उत्साही लोगों के लिए डिज़ाइन किया गया सावधानीपूर्वक नियंत्रित और पोषक तत्वों से भरपूर भोजन।",
    "Reach your weight management goals naturally with Yogyahar's low-calorie, high-fiber salads and detox programs. Enjoy calorie-conscious portions that are incredibly satisfying and delicious.": "योग्याहार के कम कैलोरी, उच्च फाइबर वाले सलाद और डिटॉक्स कार्यक्रमों के साथ स्वाभाविक रूप से अपने वजन प्रबंधन लक्ष्यों तक पहुंचें। कैलोरी-जागरूक भोजन का आनंद लें जो अविश्वसनीय रूप से संतोषजनक और स्वादिष्ट हैं।",
    "Bring wholesome nutrition to your dinner table. Yogyahar provides easy-to-digest, vitamin-rich fruit and veggie selections crafted to promote longevity, health, and vitality for your entire family.": "अपनी डाइनिंग टेबल पर पौष्टिक भोजन लाएं। योग्याहार आपके पूरे परिवार के लिए दीर्घायु, स्वास्थ्य और जीवन शक्ति को बढ़ावा देने के लिए पचाने में आसान, विटामिन युक्त फल और सब्जी के विकल्प प्रदान करता है।",
    "Customize & Schedule": "कस्टमाईज और शेड्यूल करें",
    "Fresh Daily Delivery": "दैनिक ताजा डिलीवरी",
    "Browse our menu and select a weekly or monthly subscription that matches your lifestyle.": "हमारे मेनू को ब्राउज़ करें और एक साप्ताहिक या मासिक सदस्यता चुनें जो आपकी जीवनशैली से मेल खाती हो।",
    "Our team prepares your meals fresh every morning and delivers them cold to your doorstep.": "हमारी टीम हर सुबह आपका भोजन ताजा तैयार करती है और उसे आपके दरवाजे पर ठंडा डिलीवर करती।",

    // New additions for products and sections
    "Rasahar · Juices · Subscription-based": "रासाहार · जूस · सदस्यता आधारित",
    "Regular, Seasonal & Special Juices": "नियमित, मौसमी और विशेष जूस",
    "throughout the year": "साल भर उपलब्ध",
    "available during the season": "मौसम के दौरान उपलब्ध",
    "particular months only": "केवल विशेष महीनों में",
    "Get Your Paid One-Day Trial!": "अपना सशुल्क एक-दिवसीय ट्रायल प्राप्त करें!",
    "Start Your Juice Monthly Subscription Today!": "आज ही अपनी जूस मासिक सदस्यता शुरू करें!",
    "6 Days, 6 Flavors": "6 दिन, 6 स्वाद",
    "Metabolism & Toxins Flush": "चयापचय और विषाक्त पदार्थों को बाहर निकालना",
    "100% Organic & Fresh Daily": "100% जैविक और दैनिक रूप से ताजा",
    "No Added Sugar & Preservatives": "कोई अतिरिक्त चीनी और परिरक्षक नहीं",
    "Premium Glass Bottle Delivery": "प्रीमियम ग्लास बोतल डिलीवरी",
    "Pause/Resume Plans Easily": "आसानी से योजनाओं को रोकें/पुनः आरंभ करें",
    "Salad · Subscription-based": "सलाद · सदस्यता आधारित",
    "Salad Meal, Bowl, Sprouts & Fruit Cuts": "सलाद भोजन, बाउल, स्प्राउट्स और कटे फल",
    "Fresh, premium subscription salads delivered daily. Made with crisp organic greens, nutrient-dense sprouts, fresh fruit cuts, and high-protein ingredients to keep you healthy every day.": "दैनिक रूप से डिलीवर किए जाने वाले ताजे, प्रीमियम सलाद। आपके स्वास्थ्य को बनाए रखने के लिए ताजी हरी सब्जियों, पोषक तत्वों से भरपूर स्प्राउट्स, ताजे कटे फल और उच्च-प्रोटीन सामग्री से निर्मित।",
    "Get Your One-Day Trial!": "अपना एक-दिवसीय ट्रायल प्राप्त करें!",
    "Start Your Salad's Monthly Subscription Today!": "आज ही अपनी सलाद मासिक सदस्यता शुरू करें!",
    "Non-Subscription Essentials": "गैर-सदस्यता आवश्यक चीजें",
    "Pure & Traditional Wellness Treats": "शुद्ध और पारंपरिक कल्याण उत्पाद",
    "Explore our hand-crafted, daily essentials. Made using traditional, clean methods with zero preservatives to nourish your body and soul.": "हमारे हस्तनिर्मित, दैनिक आवश्यक उत्पादों का अन्वेषण करें। आपके शरीर और आत्मा को पोषण देने के लिए बिना किसी परिरक्षक के पारंपरिक, स्वच्छ तरीकों से बनाया गया है।",

    // Testimonials and additional Detox items
    "Detox Water": "डिटॉक्स वॉटर",
    "Purify your body with our premium range of daily detox infusions. Handcrafted with fresh citrus fruits, cooling cucumber, and organic herbs to keep you hydrated and active all day long.": "दैनिक डिटॉक्स ड्रिंक्स की हमारी प्रीमियम रेंज के साथ अपने शरीर को शुद्ध करें। आपको पूरे दिन हाइड्रेटेड और सक्रिय रखने के लिए ताजे खट्टे फलों, ठंडे खीरे और जैविक जड़ी-बूटियों से निर्मित।",
    "What Our Customers Say": "हमारे ग्राहक क्या कहते हैं",
    "Real People. Real Results.": "वास्तविक लोग। वास्तविक परिणाम।",
    "Discover how YOGYAHAR is helping people across Nashik transform their health journey with daily fresh, natural, and preservative-free meals and juices.": "जानें कि कैसे योग्याहार नासिक के लोगों को दैनिक ताजे, प्राकृतिक और परिरक्षक-मुक्त भोजन और जूस के साथ उनकी स्वास्थ्य यात्रा को बदलने में मदद कर रहा है।",
    "Yogyahar's juices make me feel fresh and rejuvenated every day — sugar-free and remarkably consistent service.": "योग्याहार का जूस मुझे हर दिन तरोताजा और जीवंत महसूस कराता है - बिना चीनी के और बेहद सुसंगत सेवा।",
    "A promising start-up known for excellent service and timely delivery, every single day.": "एक आशाजनक स्टार्ट-अप जो हर एक दिन उत्कृष्ट सेवा और समय पर डिलीवरी के लिए जाना जाता है।",
    "Their morning delivery of health-promoting juice has genuinely become a part of my healthy routine.": "स्वास्थ्यवर्धक जूस की उनकी सुबह की डिलीवरी वास्तव में मेरी स्वस्थ दिनचर्या का हिस्सा बन गई है।",
    "Refreshed and fantastic! My 30-day juice cleanse with Yogyahar was a great experience.": "तरोताजा और शानदार! योग्याहार के साथ मेरा 30 दिनों का जूस डिटॉक्स एक बेहतरीन अनुभव था।",
    "Dentist": "दंत चिकित्सक",
    "Civil Engineer": "सिविल इंजीनियर",
    "Banker": "बैंकर",
    "Advisory System Analyst": "सलाहकार प्रणाली विश्लेषक",
    "Throughout the year": "साल भर उपलब्ध",
    "Yes": "हाँ",
    "No": "नहीं",
    "A refreshing blend of premium local ingredients. Designed to detox your body, improve digestion, and boost your energy levels naturally.": "प्रीमियम स्थानीय सामग्रियों का एक ताज़ा मिश्रण। आपके शरीर को डिटॉक्स करने, पाचन में सुधार करने और प्राकृतिक रूप से आपके ऊर्जा स्तर को बढ़ावा देने के लिए डिज़ाइन किया गया है।",

    // About Page Additions
    "About Yogyahar": "योग्याहार के बारे में",
    "Nourishing Nashik\nWith Pure Health": "शुद्ध स्वास्थ्य के साथ\nनासिक को पोषण देना",
    "Discover Yogyahar's fresh daily salads, cold-pressed juices, and healthy subscriptions prepared from raw, natural ingredients.": "कच्ची, प्राकृतिक सामग्रियों से तैयार योग्याहार के दैनिक ताजे सलाद, कोल्ड-प्रेस्ड जूस और स्वस्थ सदस्यताओं की खोज करें।",
    "What We Do": "हम क्या करते हैं",
    "At Yogyahar, we prepare 100% fresh fruit salads, sprout salads, vegetable salads, cold-pressed juices, smoothies, and peel-cut fruits all crafted daily with premium quality ingredients. Our aim is to make healthy eating easy, tasty, and convenient for everyone.": "योग्याहार में, हम 100% ताजे फलों के सलाद, स्प्राउट सलाद, सब्जियों के सलाद, कोल्ड-प्रेस्ड जूस, स्मूदी और छिलके कटे हुए फल तैयार करते हैं, जो प्रीमियम गुणवत्ता वाली सामग्रियों से दैनिक रूप से बनाए जाते हैं। हमारा उद्देश्य सभी के लिए स्वस्थ भोजन को आसान, स्वादिष्ट और सुविधाजनक बनाना है।",
    "Why We Started": "हमने क्यों शुरुआत की",
    "Yogyahar was founded with a simple mission: to make healthy living effortless for busy people. We realized many want to eat clean but do not have time to wash, peel, or cut fruits every day. So we created a service delivering fresh, preservative-free salads directly to your doorstep.": "योग्याहार की स्थापना एक सरल मिशन के साथ की गई थी: व्यस्त लोगों के लिए स्वस्थ जीवन को आसान बनाना। हमने महसूस किया कि कई लोग स्वच्छ खाना चाहते हैं लेकिन उनके पास हर दिन फलों को धोने, छीलने या काटने का समय नहीं होता है। इसलिए हमने सीधे आपके दरवाजे पर ताजे, परिरक्षक-मुक्त सलाद देने वाली सेवा बनाई।",
    "Delivered with Care": "देखभाल के साथ डिलीवर किया गया",
    "Every bowl is prepared in a hygienic kitchen, packed in eco-friendly biodegradable packaging, and delivered with care. We ensure that you receive nature's best – fresh, safe, and ready to enjoy directly at your home or workplace.": "हर बाउल एक स्वच्छ रसोई में तैयार किया जाता है, पर्यावरण के अनुकूल बायोडिग्रेडेबल पैकेजिंग में पैक किया जाता है, और देखभाल के साथ वितरित किया जाता है। हम सुनिश्चित करते हैं कि आपको प्रकृति का सर्वोत्तम - ताजा, सुरक्षित और सीधे आपके घर या कार्यस्थल पर आनंद लेने के लिए तैयार मिले।",
    "Always Here to Help": "मदद के लिए हमेशा तैयार",
    "From daily subscription assistance to customized orders for events, we are always here for you. Each product is packed safely and quality-checked. If you ever need help, have a query, or require a replacement, reach us anytime through call or WhatsApp.": "दैनिक सदस्यता सहायता से लेकर कार्यक्रमों के लिए कस्टमाईज्ड ऑर्डर तक, हम हमेशा आपके लिए यहां हैं। प्रत्येक उत्पाद को सुरक्षित रूप से पैक किया जाता है और गुणवत्ता-जांची जाती है। यदि आपको कभी मदद की आवश्यकता हो, कोई प्रश्न हो, या रिप्लेसमेंट की आवश्यकता हो, तो कॉल या व्हाट्सएप के माध्यम से कभी भी हमसे संपर्क करें।",
    "Seasonal mixed fruit salads": "मौसमी मिश्रित फलों का सलाद",
    "Premium & exotic fruit bowls": "प्रीमियम और विदेशी फलों के बाउल",
    "Nutritious sprout salads": "पौतिक स्प्राउट सलाद",
    "Fresh veg salads": "ताजा सब्जियों का सलाद",
    "Cold-pressed juices & smoothies": "कोल्ड-प्रेस्ड जूस और स्मूदी",
    "Custom corporate salad platters": "कस्टम कॉर्पोरेट सलाद प्लैटर",
    "Welcome to Our Fruitful Journey": "हमारी फलदायी यात्रा में आपका स्वागत है",
    "Yogyahar is a healthy food brand dedicated to delivering 100% fresh, hygienic, and preservative-free fruit salads and healthy meals right to your doorstep. We believe that healthy eating should be easy, affordable, and delicious for everyone.": "योग्याहार एक स्वास्थ्यवर्धक खाद्य ब्रांड है जो सीधे आपके दरवाजे पर 100% ताजा, स्वच्छ और परिरक्षक-मुक्त फलों के सलाद और स्वस्थ भोजन पहुंचाने के लिए समर्पित है। हमारा मानना ​​है कि स्वस्थ भोजन सभी के लिए आसान, किफायती और स्वादिष्ट होना चाहिए।",
    "We specialize in freshly prepared fruit salads, premium and exotic fruit bowls, sprout salads, vegetable salads, cold-pressed juices, smoothies, and peel-cut ready-to-eat fruits. Every order is prepared daily using premium-quality ingredients sourced from trusted suppliers.": "हम ताजा तैयार फलों के सलाद, प्रीमियम और विदेशी फलों के कटोरे, स्प्राउट सलाद, सब्जियों के सलाद, कोल्ड-प्रेस्ड जूस, स्मूदी और छिलके कटे खाने के लिए तैयार फलों में विशेषज्ञ हैं। प्रत्येक ऑर्डर को विश्वसनीय आपूर्तिकर्ताओं से प्राप्त प्रीमियम-गुणवत्ता वाली सामग्रियों का उपयोग करके दैनिक रूप से तैयार किया जाता है।",
    "Our Vision": "हमारा दृष्टिकोण",
    "Our Mission": "हमारा मिशन",
    "Celebrate Freshness, Everyday": "हर दिन ताजगी का जश्न मनाएं",
    "Discover nature's goodness with a wide range of:": "विस्तृत श्रृंखला के साथ प्रकृति की अच्छाइयों की खोज करें:",
    "Freshness, taste, and farm-fresh quality are delivered to you with every order.": "हर ऑर्डर के साथ आपको ताजगी, स्वाद और खेत जैसी ताजा गुणवत्ता प्रदान की जाती है।",
    "Order Now": "अभी ऑर्डर करें",
    "Trending now": "अभी चलन में",

    // About Page Standalone Database Seed Additions (hi)
    "ABOUT STANDALONE PAGE": "परिचय पृष्ठ",
    "Providing Wholesome Diet Nutrition Since 2018": "2018 से संपूर्ण आहार पोषण प्रदान करना",
    "Welcome to our standalone About page! We make fresh, natural, hygienic, tasty, authentic diet food. We believe in selling Taste, Time, Knowledge, Variety, and Consistency.": "हमारे परिचय पृष्ठ पर स्वागत है! हम ताजा, प्राकृतिक, स्वच्छ, स्वादिष्ट, प्रामाणिक आहार भोजन बनाते हैं। हम स्वाद, समय, ज्ञान, विविधता और निरंतरता प्रदान करने में विश्वास करते हैं।",
    "\"Nourishing your body with local healthy products, delivered fresh daily.\"": "\"स्थानीय स्वास्थ्यवर्धक उत्पादों के साथ आपके शरीर का पोषण, दैनिक रूप से ताजा वितरित।\"",
    "Back to All Articles": "सभी लेखों पर वापस जाएं",
    "Table of Contents": "विषय-सूची",
    "Introduction": "प्रस्तावना",
    "Core Health Benefits": "मुख्य स्वास्थ्य लाभ",
    "Ayurvedic Recommendations": "आयुर्वेदिक सिफारिशें",
    "Routine Incorporation": "दिनचर्या में शामिल करना",
    "Reading time:": "पढ़ने का समय:",
    "Enjoyed this article?": "क्या आपको यह लेख पसंद आया?",
    "Subscribe to fresh cold-pressed juices and high-protein salad meals delivered daily in Nashik.": "नासिक में रोजाना डिलीवर किए जाने वाले ताजे कोल्ड-प्रेस्ड जूस और हाई-प्रोटीन सलाद का सब्सक्रिप्शन लें।",
    "Explore Fresh Products": "ताजा उत्पाद देखें",
    "More Articles You Might Like": "अन्य लेख जो आपको पसंद आ सकते हैं",
    "Read article": "लेख पढ़ें",
    "Why Cold-Pressed Juices Are Superior for Daily Detox & Energy": "दैनिक डिटॉक्स और ऊर्जा के लिए कोल्ड-प्रेस्ड जूस क्यों बेहतर हैं",
    "Discover how cold-pressed extraction preserves vital living enzymes, vitamins, and antioxidants compared to conventional centrifugal blending.": "खोजें कि कैसे कोल्ड-प्रेस्ड निष्कर्षण पारंपरिक सेंट्रीफ्यूगल ब्लेंडिंग की तुलना में महत्वपूर्ण जीवित एंजाइमों, विटामिनों और एंटीऑक्सीडेंट को सुरक्षित रखता है।",
    "The Power of High-Protein Salads in Sustainable Weight Loss": "सतत वजन घटाने में उच्च-प्रोटीन सलाद की ताकत",
    "Learn how pairing raw microgreens, sprouts, organic seeds, and plant proteins keeps you satisfied, regulates blood sugar, and boosts metabolism.": "जानें कि कैसे कच्चे माइक्रोग्रीन्स, स्प्राउट्स, जैविक बीजों और पौधों के प्रोटीन का सेवन आपको संतुष्ट रखता है, रक्त शर्करा को नियंत्रित करता है और चयापचय को बढ़ावा देता है।",
    "5 Simple Ayurvedic Habits for Natural Digestion & High Energy": "प्राकृतिक पाचन और उच्च ऊर्जा के लिए 5 सरल आयुर्वेदिक आदतें",
    "Integrate ancient Dinacharya wellness principles into modern daily schedules for improved Agni (digestive fire) and mental clarity.": "बेहतर अग्नि (पाचन तंत्र) और मानसिक स्पष्टता के लिए आधुनिक दैनिक दिनचर्या में प्राचीन दिनचर्या कल्याण सिद्धांतों को एकीकृत करें।",
    "Super Laddus: The Guilt-Free Energy Snack for Busy Professionals": "सुपर लड्डू: व्यस्त पेशेवरों के लिए अपराध-मुक्त ऊर्जा स्नैक",
    "Handcrafted from premium dry fruits, seeds, and wood-pressed ghee without refined sugar—the perfect healthy snack for active lifestyles.": "बिना रिफाइंड चीनी के प्रीमियम सूखे मेवों, बीजों और लकड़ी-घानी के घी से हस्तनिर्मित - सक्रिय जीवनशैली के लिए एकदम सही स्वस्थ स्नैक।",
    "Dr. Ananya Sharma": "डॉ. अनन्या शर्मा",
    "Ayurvedic Practitioner & Wellness Lead": "आयुर्वेदिक चिकित्सक और कल्याण प्रमुख",
    "Chef Rohan Deshmukh": "शेफ रोहन देशमुख",
    "Nutrition & Culinary Lead": "पोषण और पाक कला प्रमुख",
    "Vaidya Suresh Patil": "वैद्य सुरेश पाटिल",
    "Ayurvedic Doctor": "आयुर्वेदिक डॉक्टर",
    "Team Yogyahar": "टीम योग्याहार",
    "Wellness & Nutrition Team": "कल्याण एवं पोषण टीम",
    "4 min read": "4 मिनट का वाचन",
    "5 min read": "5 मिनट का वाचन",
    "6 min read": "6 मिनट का वाचन",
    "Read Full Article": "पूरा लेख पढ़ें",
    "Table of Contents": "विषय-सूची",
    "1. Introduction": "1. प्रस्तावना",
    "2. Core Health Benefits": "2. मुख्य स्वास्थ्य लाभ",
    "3. Ayurvedic Recommendations": "3. आयुर्वेदिक सिफारिशें",
    "4. Routine Incorporation": "4. दिनचर्या में शामिल करना",
    "1. Satiety & Energy": "1. तृप्ति और ऊर्जा",
    "2. The Salad Blueprint": "2. सलाद खाका",
    "3. Smart Dressings": "3. स्मार्ट ड्रेसिंग",
    "1. Agni Principles": "1. अग्नि सिद्धांत",
    "2. The 5 Daily Habits": "2. 5 दैनिक आदतें",
    "3. Healthy Routine Planning": "3. स्वस्थ दिनचर्या योजना",
    "1. Midday Fatigue": "1. दोपहर की थकान",
    "2. Nutritional Profile": "2. पोषण प्रोफ़ाइल",
    "3. Delivery Information": "3. वितरण जानकारी",
    "Enjoyed this article?": "क्या आपको यह लेख पसंद आया?",
    "Subscribe to fresh cold-pressed juices and high-protein salad meals delivered daily in Nashik.": "नासिक में दैनिक रूप से डिलीवर किए जाने वाले ताजे कोल्ड-प्रेस्ड जूस और उच्च-प्रोटीन सलाद भोजन का सब्सक्रिप्शन लें।",
    "Explore Fresh Products": "ताजा उत्पाद देखें",
    "Want to try our custom Salads?": "क्या आप हमारे कस्टम सलाद आजमाना चाहते हैं?",
    "Order our customized high-protein bowls packed with seeds, sprouts, and premium vegetables.": "बीजों, स्प्राउट्स और प्रीमियम सब्जियों से भरपूर हमारे कस्टमाइज्ड उच्च-प्रोटीन बाउल ऑर्डर करें।",
    "Order Salads Now": "अभी सलाद ऑर्डर करें",
    "Get Ayurvedic Consultation": "आयुर्वेदिक परामर्श प्राप्त करें",
    "Connect with our certified practitioners to understand your body constitution (Dosha) and diet map.": "अपने शरीर की संरचना (दोष) और डाइट चार्ट को समझने के लिए हमारे प्रमाणित चिकित्सकों से जुड़ें।",
    "Consult Now": "अभी परामर्श करें",
     "Browse Laddus": "लड्डू देखें",
    "In recent years, cold-pressed juices have evolved from a trendy health wellness routine into a scientifically-proven nutritional staple. But what makes cold-pressed juicing fundamentally superior to traditional centrifugal juicers?": "हाल के वर्षों में, कोल्ड-प्रेस्ड जूस एक ट्रेंडी हेल्थ वेलनेस रूटीन से बढ़कर एक वैज्ञानिक रूप से सिद्ध पोषण संबंधी मुख्य भोजन बन गया है। लेकिन कोल्ड-प्रेस्ड जूस पारंपरिक सेंट्रीफ्यूगल जूसर की तुलना में मौलिक रूप से श्रेष्ठ क्यों है?",
    "The Science Behind Cold-Pressed Hydraulic Extraction": "कोल्ड-प्रेस्ड हाइड्रोलिक निष्कर्षण के पीछे का विज्ञान",
    "Unlike traditional high-speed juicers whose spinning blades create heat friction and drag massive amounts of air into the liquid—causing rapid oxidation and heat degradation of delicate vitamins—cold-pressed hydraulic extraction gently presses fresh fruits and vegetables under tons of pressure without heat exposure.": "पारंपरिक हाई-स्पीड जूसर के विपरीत, जिनके घूमते हुए ब्लेड गर्मी घर्षण पैदा करते हैं और तरल में भारी मात्रा में हवा खींचते हैं (जिससे नाजुक विटामिन का तेजी से ऑक्सीकरण और गर्मी का क्षरण होता है), कोल्ड-प्रेस्ड हाइड्रोलिक निष्कर्षण बिना गर्मी के संपर्क के टन दबाव के तहत ताजे फलों और सब्जियों को धीरे से दबाता है।",
    "Key Health Benefits of Daily Juicing": "दैनिक जूस पीने के प्रमुख स्वास्थ्य लाभ",
    "Maximum Bioavailability:": "अधिकतम जैव उपलब्धता:",
    "Retains up to 3x more vitamins A, C, E, and plant antioxidants.": "3 गुना अधिक विटामिन ए, सी, ई और पौधों के एंटीऑक्सीडेंट को बनाए रखता है।",
    "Cellular Absorption:": "कोशिकीय अवशोषण:",
    "Allows your digestive system a resting window while delivering instant hydration directly into your bloodstream.": "आपके रक्तप्रवाह में सीधे त्वरित जलयोजन प्रदान करते हुए आपकी पाचन प्रणाली को आराम देने का अवसर देता है।",
    "100% Pure:": "100% शुद्ध:",
    "No added refined sugar, artificial flavors, preservatives, or diluting concentrates.": "कोई अतिरिक्त रिफाइंड चीनी, कृत्रिम स्वाद, परिरक्षक या पानी का मिश्रण नहीं।",
    "How to Integrate Cold-Pressed Juices into Your Life": "कोल्ड-प्रेस्ड जूस को अपने जीवन में कैसे एकीकृत करें",
    "We recommend enjoying a 300ml bottle of fresh <em>Carrot-Beet-Ginger</em> or <em>Amla Green Juice</em> every morning on an empty stomach to kickstart your metabolism and boost immunity.": "हम आपके चयापचय को शुरू करने और प्रतिरक्षा को बढ़ावा देने के लिए हर सुबह खाली पेट ताजे <em>गाजर-बीट-अदरक</em> या <em>आंवला ग्रीन जूस</em> की 300 मिलीलीटर की बोतल का आनंद लेने की सलाह देते है।",
    "Sustainable weight loss isn't about restrictive starvation; it's about supplying high-density micro-nutrients that satisfy your body's cellular hunger and stabilize energy.": "टिकाऊ वजन कम करना प्रतिबंधात्मक भुखमरी के बारे में नहीं है; यह उच्च घनत्व वाले सूक्ष्म पोषक तत्वों की आपूर्ति करने के बारे में है जो आपके शरीर की कोशिकीय भूख को संतुष्ट करते हैं और ऊर्जा को स्थिर करते हैं।",
    "Anatomy of a High-Protein Salad Meal": "एक उच्च-प्रोटीन सलाद भोजन की शारीरिक रचना",
    "Combining sprouted grains, crisp seasonal greens, and cold-pressed seeds provides a complete amino-acid profile while offering rich dietary fiber.": "अंकुरित अनाज, कुरकुरी मौसमी हरी सब्जियों और कोल्ड-प्रेस्ड बीजों का संयोजन प्रचुर मात्रा में आहार फाइबर प्रदान करते हुए एक पूर्ण अमीनो-एसिड प्रोफाइल प्रदान करता है।",
    "Key Ingredients for Satiety": "तृप्ति के लिए मुख्य सामग्री",
    "Sprouted Mung & Chickpeas:": "अंकुरित मूंग और चने:",
    "High-protein, easily digestible bio-active nutrients.": "उच्च प्रोटीन, आसानी से पचने योग्य जैव-सक्रिय पोषक तत्व।",
    "Walnuts & Pumpkin Seeds:": "अखरोट और कद्दू के बीज:",
    "Healthy Omega-3 fats for brain clarity and heart health.": "मस्तिष्क की स्पष्टता और हृदय स्वास्थ्य के लिए स्वस्थ ओमेगा -3 फैट।",
    "Raw Leafy Greens:": "कच्ची पत्तेदार सब्जियां:",
    "Loaded with natural chlorophyl and essential minerals.": "प्राकृतिक क्लोरोफिल और आवश्यक खनिजों से भरपूर।",
    "In Ayurveda, a strong <em>Agni</em> (digestive fire) is considered the cornerstone of physical longevity, clear skin, and vibrant mental clarity. Without balanced digestion, even the healthiest foods cannot be fully assimilated by the body's tissues.": "आयुर्वेद में, एक मजबूत <em>अग्नि</em> (पाचक अग्नि) को शारीरिक दीर्घायु, साफ त्वचा और जीवंत मानसिक स्पष्टता का आधार माना जाता है। संतुलित पाचन के बिना, स्वास्थ्यप्रद खाद्य पदार्थों को भी शरीर के ऊतकों द्वारा पूरी तरह से अवशोषित नहीं किया जा सकता है।",
    "Understanding Agni: The Centerpiece of Health": "अग्नि को समझना: स्वास्थ्य का केंद्रबिंदू",
    "According to the classical text <em>Charak Samhita</em>, Agni governs not just digestion but also our internal heat, cellular intelligence, and mental energy. When Agni is weak (Mandagni), it creates a toxic metabolic byproduct known as <strong>Ama</strong>, which is the root cause of chronic sluggishness and physical discomfort.": "क्लासिक पाठ <em>चरक संहिता</em> के अनुसार, अग्नि न केवल पाचन बल्कि हमारी आंतरिक गर्मी, कोशिकीय बुद्धिमत्ता और मानसिक ऊर्जा को भीं नियंत्रित करती है। जब अग्नि कमजोर होती है (मंदाग्नि), तो यह एक विषाक्त चयापचय सह-उत्पाद बनाती है जिसे <strong>आम (Ama)</strong> कहा जाता है, जो पुरानी सुस्ती और शारीरिक परेशानी का मूल कारण है।",
    "5 Habits to Practice Daily": "दैनिक अभ्यास करने के लिए 5 आदतें",
    "Copper Vessel Water:": "तांबे के बर्तन का पानी:",
    "Hydrate with copper-infused water (Tamra Jal) first thing in the morning to balance all three Doshas (Vata, Pitta, and Kapha).": "तीनों दोषों (वात, पित्त और कफ) को संतुलित करने के लिए सुबह सबसे पहले तांबे के पानी (ताम्र जल) से खुद को हाइड्रेट करें।",
    "Eat Fresh & Seasonal:": "ताजा और मौसमी खाएं:",
    "Align your dietary choices with seasonal fruits and vegetables to keep your gut microbiome resilient.": "अपने पेट के माइक्रोबायोम को लचीला बनाए रखने के लिए अपने आहार विकल्पों को मौसमी फलों और सब्जियों के साथ संरेखित करें।",
    "Main Meal at Midday:": "दोपहर का मुख्य भोजन:",
    "Eat your largest meal when Agni is naturally strongest at noon, matching the highest position of the sun.": "जब अग्नि स्वाभाविक रूप से दोपहर में सबसे मजबूत हो, तब अपना सबसे बड़ा भोजन खाएं, जो सूर्य की सबसे ऊंची स्थिति से मेल खाता है।",
    "Mindful Chewing:": "जागरूकता से चबाना:",
    "Chew each bite thoroughly to initiate salivary digestive enzymes and prevent bloating.": "लार वाले पाचक एंजाइमों को शुरू करने और सूजन को रोकने के लिए प्रत्येक निवाले को अच्छी तरह से चबाएं।",
    "Early Dinner Window:": "जल्दी रात का भोजन:",
    "Finish dinner early (before 8 PM) to allow complete cellular healing and detoxification overnight.": "रात भर में पूर्ण कोशिकीय उपचार और विषहरण की अनुमति देने के लिए रात का भोजन जल्दी (रात 8 बजे से पहले) समाप्त करें।",
    "Healthy Routine Planning": "स्वस्थ दिनचर्या योजना",
    "To transition into an Ayurvedic schedule, begin by drinking warm water with lemon and ginger slices in the morning to stimulate peristalsis. Next, replace heavy cold breakfasts with warm, freshly cooked grains or hot herbal teas. By respecting your body's circadian rhythm, you will experience natural weight regulation and sustained mental clarity throughout the day.": "आयुर्वेदिक कार्यक्रम में बदलाव करने के लिए, सुबह नींबू और अदरक के स्लाइस के साथ गर्म पानी पीने से शुरुआत करें। इसके बाद, भारी ठंडे नाश्ते को गर्म, ताजे पके हुए अनाज या गर्म हर्बल चाय से बदलें। अपने शरीर की प्राकृतिक लय का सम्मान करके, आप प्राकृतिक वजन नियंत्रण और पूरे दिन निरंतर मानसिक स्पष्टता का अनुभव करेंगे।",
    "Mid-afternoon energy crashes often drive us toward processed sugary snacks. Yogyahar Super Laddus are handcrafted to deliver sustained vitality with zero guilt.": "दोपहर के समय ऊर्जा में गिरावट अक्सर हमें प्रसंस्कृत शर्करा युक्त स्नैक्स की ओर ले जाती है। योग्याहार सुपर लड्डू बिना किसी अपराधबोध के निरंतर जीवन शक्ति प्रदान करने के लिए हस्तनिर्मित हैं।",
    "Combating Midday Fatigue Naturally": "दोपहर की थकान का प्राकृतिक रूप से मुकाबला",
    "For most corporate professionals and active individuals, 4:00 PM is a challenging hour. Traditional options like caffeine, refined sugar cookies, and fried snacks cause quick insulin spikes followed by rapid exhaustion. Super Laddus solve this problem by leveraging complex plant-based carbohydrates and healthy fats that release energy slowly into your bloodstream.": "अधिकांश कॉर्पोरेट पेशेवरों और सक्रिय व्यक्तियों के लिए, शाम 4:00 बजे का समय एक चुनौतीपूर्ण समय होता है। कैफीन, रिफाइंड चीनी कुकीज़ और तले हुए स्नैक्स जैसे पारंपरिक विकल्प त्वरित इंसुलिन स्पाइक्स का कारण बनते हैं जिसके बाद तेजी से थकावट होती है। सुपर लड्डू जटिल पौधे-आधारित कार्बोहाइड्रेट और स्वस्थ वसा का लाभ उठाकर इस समस्या को हल करते हैं जो आपके रक्तप्रवाह में धीरे-धीरे ऊर्जा छोड़ते हैं।",
    "Nutritional Profile: What's Inside?": "पोषण प्रोफ़ाइल: अंदर क्या है?",
    "Each Yogyahar Super Laddu is a compact power cell containing:": "प्रत्येक योग्याहार सुपर लड्डू एक कॉम्पैक्ट पावर सेल है जिसमें शामिल है:",
    "Premium Dry Fruits:": "प्रीमियम सूखे मेवे:",
    "Walnuts, almonds, and cashews packed with minerals.": "खनिजों से भरपूर अखरोट, बादाम और काजू।",
    "Organic Seed Blend:": "जैविक बीजों का मिश्रण:",
    "Pumpkin seeds, flaxseeds, and sunflower seeds containing rich Omega-3 fatty acids.": "कद्दू के बीज, अलसी के बीज और सूरजमुखी के बीज जिनमें प्रचुर मात्रा में ओमेगा -3 फैटी एसिड होता है।",
    "Natural Sweeteners:": "प्राकृतिक मिठास:",
    "Dates and raw figs with no refined cane sugar.": "बिना रिफाइंड चीनी के खजूर और कच्चे अंजीर।",
    "Local Wood-Pressed Ghee:": "स्थानीय लकड़ी-घानी घी:",
    "Promotes lubricating joints and supports absorption of fat-soluble vitamins.": "जोड़ों के स्वास्थ्य को बढ़ावा देता है और वसा में घुलनशील विटामिन के अवसोंषण का समर्थन करता है।",
    "Fresh Doorstep Delivery": "ताजा घर तक डिलीवरी",
    "Prepared in small batches under hygienic conditions, our laddus are delivered directly across Nashik so you always have a pack of healthy fuel ready at your desk or home pantry.": "स्वच्छ परिस्थितियों में छोटे बैचों में तैयार, हमारे लड्डू सीधे पूरे नासिक में वितरित किए जाते हैं ताकि आपके पास हमेशा अपने डेस्क या घर की रसोई में स्वस्थ ईंधन का एक पैकेट तैयार रहेियों में छोटे बैचों में तैयार, हमारे लड्डू सीधे पूरे नासिक में वितरित किए जाते हैं ताकि आपके पास हमेशा अपने डेस्क या घर की रसोई में स्वस्थ ईंधन का एक पैकेट तैयार रहे।",
    "FAQ": "सामान्य प्रश्न",
    "Frequently Asked Questions": "अक्सर पूछे जाने वाले प्रश्न",
    "Our Vision": "हमारा दृष्टिकोण",
    "Our Mission": "हमारा मिशन",
    "Explore Our Fresh Selections": "हमारे ताज़ा विकल्पों का अन्वेषण करें",
    "Fruit bowls, juices, and tropical picks – all in one place.": "फलों के कटोरे, जूस और उष्णकटिबंधीय विकल्प - सब एक ही स्थान पर।",
    "Hide Filters": "फ़िल्टर छुपाएं",
    "Show Filters": "फ़िल्टर दिखाएं",
    "results": "परिणाम",
    "Filters": "फ़िल्टर",
    "(Refine search)": "(खोज को परिष्कृत करें)",
    "Availability": "उपलब्धता",
    "In stock": "स्टॉक में है",
    "Category": "श्रेणी",
    "Diet Goal": "आहार का लक्ष्य",
    "All Diet Goals": "सभी आहार लक्ष्य",
    "Weight Loss": "वजन घटाना",
    "Detox": "डिटॉक्स",
    "Muscle Gain": "मांसपेशियों का विकास",
    "General Health": "सामान्य स्वास्थ्य",
    "Delivery Slots": "वितरण का समय",
    "All Slots": "सभी समय स्लॉट",
    "Morning (6-9 AM)": "सुबह (6-9 AM)",
    "Evening (5-7 PM)": "शाम (5-7 PM)",
    "Both Slots": "दोनों समय स्लॉट",
    "Need Help?": "मदद चाहिए?",
    "Questions about a product? Our team is happy to guide you.": "किसी उत्पाद के बारे में प्रश्न? हमारी टीम आपका मार्गदर्शन करने के लिए तैयार है।",
    "Chat on WhatsApp": "व्हाट्सएप पर चैट करें",
    "SHOWING": "दिखा रहा है",
    "OF": "का",
    "RESULTS": "परिणाम",
    "Default sorting": "डिफ़ॉल्ट सॉर्टिंग",
    "Sort by price: low to high": "कीमत के अनुसार: कम से उच्च",
    "Sort by price: high to low": "कीमत के अनुसार: उच्च से कम",
    "Sort by name: A-Z": "नाम के अनुसार: A-Z",
    "No products found matching filters.": "फ़िल्टर से मेल खाता कोई उत्पाद नहीं मिला।",
    "OUT OF STOCK": "स्टॉक में नहीं",
    "Upcoming": "आगामी",
    "Active": "सक्रिय",
    "In Stock": "स्टॉक में",
    "Out of Stock": "आउट ऑफ स्टॉक",
    "Plans from ₹1,000": "₹1,000 से योजनाएं",
    "View Product": "उत्पाद देखें",
    "NEXT >": "अगला >",
    "Trending now": "ट्रेंडिंग उत्पाद",
    "Our Offerings": "हमारी पेशकश",
    "📍 Serviceable in whole Nasik area!": "📍 पूरे नासिक क्षेत्र में सेवा योग्य!",
    "Who Is This For?": "यह किसके लिए है?",
    "Yogyahar is crafted for everyone looking to transform their relationship with food and embrace vitality.": "योग्याहार उन सभी के लिए तैयार किया गया है जो भोजन के साथ अपने संबंधों को बदलना और जीवन शक्ति अपनाना चाहते हैं।",
    "Ready to Begin Your Healthy Lifestyle?": "क्या आप अपनी स्वस्थ जीवनशैली शुरू करने के लिए तैयार हैं?",
    "Choose Yogyahar and enjoy dietitian-curated, delicious salads delivered daily.": "योग्याहार चुनें और प्रतिदिन वितरित किए जाने वाले पोषण विशेषज्ञ-क्यूरेटेड, स्वादिष्ट सलाद का आनंद लें।",
    "Custom Inquiry": "कस्टम पूछताछ",
    "Delivered Fresh": "ताजा वितरण",
    "At your doorstep": "आपके दरवाजे पर",
    "Secure Payment": "सुरक्षित भुगतान",
    "100% safe & secure": "100% सुरक्षित और संरक्षित",
    "Subscription Plans": "सदस्यता योजनाएं",
    "Save more with plans": "योजनाओं के साथ अधिक बचत करें",
    "100% Satisfaction": "100% संतुष्टि",
    "We care for you": "हम आपकी परवाह करते हैं",
    "Yogyahar AI Assistant": "योग्याहार एी सहायक",
    "Online • Instant Health Answers": "ऑनलाइन • तत्काल स्वास्थ्य उत्तर",
    "Reset Chat": "चैट रीसेट करें",
    "Close Chat": "चैट बंद करें",
    "Ask about diet, plans, juices...": "आहार, योजना, जूस के बारे में पूछें...",
    "Chat with AI": "एआई के साथ चैट करें",
    "Namaste! 🙏 Welcome to Yogyahar! I'm your AI Health Assistant. How can I help you with our fresh diet meals, fruit bowls, or subscription plans today?": "नमस्ते! 🙏 योग्याहार में आपका स्वागत है! मैं आपका एआई स्वास्थ्य सहायक हूं। आज मैं हमारे ताजा आहार भोजन, फलों के कटोरे, या सदस्यता योजनाओं के साथ आपकी कैसे मदद कर सकता हूं?",
    "🥗 What subscription plans do you offer?": "🥗 आप कौन सी सदस्यता योजनाएं प्रदान करते हैं?",
    "🌿 Are your juices 100% natural?": "🌿 क्या आपके जूस 100% प्राकृतिक हैं?",
    "🚚 Do you deliver across Nashik?": "🚚 क्या आप पूरे नासिक में डिलीवरी करते हैं?",
    "📞 How can I connect or place an order?": "📞 मैं कैसे जुड़ सकता हूं या ऑर्डर दे सकता हूं?",
    "What Customers Say": "हमारे ग्राहक क्या कहते हैं",
    "What Experts Say": "विशेषज्ञ क्या कहते हैं",
    "One-Day Trial": "एक-दिवसीय ट्रायल",
    "View Details": "विवरण देखें",
    "Made with natural, wholesome ingredients": "प्राकृतिक, स्वास्थ्यवर्धक अवयवों से निर्मित",
    "Wood pressed & chemical free": "लकड़ी-घानी से निकाला गया और रसायन मुक्त",
    "Morning Slot": "सुबह का समय",
    "Evening Slot": "शाम का समय",
    "6–9 AM": "6-9 AM",
    "5–7 PM": "5-7 PM",
    "Ingredients": "सामग्री",
    "Advantages": "लाभ",
    "Precautions": "सावधानियां",
    "Not Suitable For": "इनके लिए उपयुक्त नहीं",
    "100% Pure": "100% शुद्ध",
    "Cold Pressed": "कोल्ड प्रेस्ड",
    "Fresh Delivery": "ताजा डिलीवरी",
    "Diet Friendly": "आहार अनुकूल",
    "Still have a Question? Chat with Us": "अब भी कोई सवाल है? हमसे चैट करें",
    "Quick Links": "त्वरित लिंक",
    "Juices": "जूस",
    "Detox Water": "डिटॉक्स वॉटर",
    "Salads & Fruit Cuts": "सलाद और कटे फल",
    "Super Laddu": "सुपर लड्डू",
    "Cold Pressed Oil": "कोल्ड प्रेस्ड ऑयल",
    "You can connect directly on": "आप सीधे इस नंबर पर संपर्क कर सकते हैं",
    "We Deliver At": "हम यहाँ डिलीवरी करते हैं",
    "Home": "घर",
    "School": "स्कूल",
    "College": "कॉलेज",
    "Office": "कार्यालय",
    "Gym": "जिम",
    "Hospitals": "अस्पताल",
    "Dr. Rupali Pade": "डॉ. रूपाली पाडे",
    "Rishikesh Sonawane": "ऋषिकेश सोनावणे",
    "Ujjwala Kiran Petkar": "उज्ज्वला किरण पेटकर",
    "Rahul Bhamre": "राहुल भामरे",
    "Fresh Carrots, Touch of Ginger, Lemon Juice": "ताजी गाजर, अदरक का स्पर्श, नींबू का रस",
    "Ingredients List": "सामग्री सूची",
    "Fresh, healthy, 100% organic juice": "ताजा, स्वस्थ, 100% जैविक जूस",
    "Product Status": "उत्पाद की स्थिति",
    "Products Includes": "उत्पाद में शामिल",
    "Available Quantities": "उपलब्ध मात्रा",
    "Single Product": "एकल उत्पाद",
    "Combination of Multiple Products": "कई उत्पादों का संयोजन",
    "200 ml / 300 ml / 500 ml": "200 मिली / 300 मिली / 500 मिली",
    "200 gm / 450 gm": "200 ग्राम / 450 ग्राम",
    "Important Precautions": "महत्वपूर्ण सावधानियां",
    "Infants under 1 year, or individuals with severe kidney conditions.": "1 वर्ष से कम उम्र के शिशु, या गंभीर गुर्दे की स्थिति वाले व्यक्ति।",
    "Consult doctor if managing high potassium or kidney conditions.": "उच्च पोटेशियम या गुर्दे की स्थिति का प्रबंधन करने पर डॉक्टर से परामर्श करें।",
    "Regular": "नियमित",
    "Seasonal": "मौसमी",
    "Special": "विशेष",
    "Available throughout the year": "साल भर उपलब्ध",
    "Available during the season": "मौसम के दौरान उपलब्ध",
    "Available in particular months only": "केवल विशेष महीनों में उपलब्ध"
  },
  mr: {
    // Nav links & common
    "Home": "मुख्य पान",
    "Products": "उत्पादने",
    "Services": "सेवा",
    "About Us": "आमच्याबद्दल",
    "Contact Us": "संपर्क साधा",
    "Connect Now!": "आत्ताच संपर्क करा!",
    "Explore Products": "उत्पादने पहा",
    "Subscribe on WhatsApp →": "व्हाट्सएपवर सबस्क्राईब करा →",
    "Order on WhatsApp": "व्हाट्सएपवर ऑर्डर करा",
    "Enquire on WhatsApp →": "व्हाट्सएपवर चौकशी करा →",
    "Enquire on WhatsApp &rarr;": "व्हाट्सएपवर चौकशी करा →",
    "In Stock": "स्टॉकमध्ये उपलब्ध",
    "Out of Stock": "स्टॉकमध्ये नाही",
    "Active": "सक्रिय",
    "Inactive": "निष्क्रिय",
    "Type of Making": "बनवण्याची पद्धत",
    "Available": "उपलब्धता",
    "Suitable for Fast": "उपवासासाठी योग्य",
    "Stock Status": "स्टॉकची स्थिती",
    "Product Specifications": "उत्पादन तपशील",
    "Subscription Packages": "सदस्यता पॅकेजेस",
    "1 Day Plan": "1 दिवसाचा प्लॅन",
    "6 Days Plan": "6 दिवसांचा प्लॅन",
    "25 Days Plan": "25 दिवसांचा प्लॅन",
    "Trust Builder": "विश्वास निर्माता",
    "Most Popular": "सर्वात लोकप्रिय",
    "Best Seller": "बेस्ट सेलर",
    "Cleanse. Refresh. Rejuvenate.": "स्वच्छ. ताजे. टवटवीत.",
    "Health & Nutritional Benefits": "आरोग्य आणि पौष्टिक फायदे",
    "Precautions (Not suitable for / Who should not consume)": "काळजी (कोणासाठी योग्य नाही / कोणी खाऊ नये)",
    "Available Varieties": "उपलब्ध प्रकार",
    "You May Also Like": "तुम्हाला हे देखील आवडेल",
    "Delivered Fresh": "ताजी डिलिव्हरी",
    "At your doorstep": "तुमच्या दारापर्यंत",
    "Secure Payment": "सुरक्षित पेमेंट",
    "100% safe & secure": "100% सुरक्षित",
    "Subscription Plans": "सदस्यता योजना",
    "Save more with plans": "प्लॅन्ससह अधिक बचत करा",
    "100% Satisfaction": "100% समाधान",
    "We care for you": "आम्ही तुमची काळजी घेतो",

    // Hero
    "YOGYAHAR — Follow Your Diet With Us!": "योग्याहार — आमच्यासोबत आपल्या आहाराचे पालन करा!",
    "Fresh. Natural. Hygienic.": "ताजे. नैसर्गिक. स्वच्छ.",
    "Tasty. Authentic.": "चवदार. अस्सल.",
    "No preservatives, no chemicals, no artificial colors, no added sugar, only Pure Products.": "कोणतेही परिरक्षक नाही, कोणतेही रसायन नाही, कोणतेही कृत्रिम रंग नाही, कोणतीही अतिरिक्त साखर नाही, फक्त शुद्ध उत्पादने.",
    "Fresh & Natural": "ताजे आणि नैसर्गिक",
    "No Chemicals": "केमिकल्स विरहित",
    "No Preservatives": "परिरक्षक विरहित",
    "No Added Sugar": "अतिरिक्त साखर विरहित",
    "Doorstep Delivery": "दारापर्यंत डिलिव्हरी",
    "Across Nashik": "संपूर्ण नाशिकमध्ये",
    "100% Vegetarian": "100% शाकाहारी",
    "Made to Order": "ऑर्डरनुसार बनवलेले",

    // About Us (Home)
    "Good Health Starts with the Right Choice!": "चांगले आरोग्य योग्य निवडीने सुरू होते!",
    "Since 2018, YOGYAHAR makes fresh, natural, hygienic, tasty, authentic diet food — protein-packed salads, cold-pressed juices, and ready-to-eat/ready-to-cook meal kits. We believe in selling Taste, Time, Knowledge, Variety, and Consistency.": "2018 पासून, योग्याहार ताजे, नैसर्गिक, स्वच्छ, चवदार, अस्सल डाएट फूड बनवते - प्रोटीनयुक्त कोशिंबीर (सलाड), कोल्ड-प्रेस्ड ज्यूस आणि खाण्यासाठी तयार/शिजवण्यासाठी तयार जेवण किट. आमचा चव, वेळ, ज्ञान, विविधता आणि सुसंगतता विकण्यावर विश्वास आहे.",
    "\"We Don't Just Serve Food, We Serve a Healthier You!\"": "\"आम्ही फक्त अन्न वाढत नाही, आम्ही तुमच्या आरोग्याची काळजी घेतो!\"",
    "To make available Fresh, Natural, Hygienic, Tasty, and Authentic diet food anytime at possible location.": "ताजे, नैसर्गिक, स्वच्छ, चवदार आणि अस्सल आहार अन्न कोणत्याही वेळी योग्य ठिकाणी उपलब्ध करून देणे.",
    "To create a healthy nation by serving diet food at an affordable cost with a sustainable business model.": "किफायतशीर दरात आहार अन्न देऊन एक निरोगी राष्ट्र निर्माण करणे.",

    // Ayurveda Quote
    "Charak Samhita · Sutra 30.26": "चरक संहिता · सूत्र 30.26",
    "स्वस्थस्य स्वास्थ्य रक्षणं । आतुरस्य विकार प्रशमनं च ॥": "स्वस्थस्य स्वास्थ्य रक्षणं । आतुरस्य विकार प्रशमनं च ॥",
    "आयुर्वेद का मुख्य उद्देश्य स्वस्थ लोगों के स्वास्थ्य को बनाए रखना और बीमार लोगों की बीमारी को ठीक करना है।": "आयुर्वेद का मुख्य उद्देश्य स्वस्थ लोगों के स्वास्थ्य को बनाए रखना और बीमार लोगों की बीमारी को ठीक करना है।",
    "\"The main purpose of Ayurveda is to maintain the health of the healthy and to cure the disease of the ill.\"": "\"आयुर्वेदाचा मुख्य उद्देश निरोगी लोकांचे आरोग्य राखणे आणि आजारी लोकांचे आजार बरे करणे हा आहे.\"",

    // Stats
    "Registered Happy Customers": "नोंदणीकृत आनंदी ग्राहक",
    "Salads and Juices": "सलाड आणि ज्यूस",
    "Km of Daily Doorstep Delivery": "दैनिक दारापर्यंत डिलिव्हरी (किमी)",
    "Direct-Indirect Employment": "थेट-अप्रत्यक्ष रोजगार",

    // How It Works
    "How It Works": "हे कसे कार्य करते",
    "Clean Eating, Made Simple": "स्वच्छ आहार, आता सोपा",
    "We make healthy living easy with a simple and efficient process.": "आम्ही साध्या आणि कार्यक्षम प्रक्रियेद्वारे निरोगी जीवन सोपे करतो.",
    "Choose Your Plan": "तुमचा प्लॅन निवडा",
    "Trial, 6-day or 25-day subscription": "ट्रायल, 6-दिवस किंवा 25-दिवसांची सदस्यता",
    "Order on WhatsApp": "व्हाट्सएपवर ऑर्डर करा",
    "Message us to place or customize your order": "ऑर्डर करण्यासाठी किंवा कस्टमाइझ करण्यासाठी आम्हाला मेसेज करा",
    "We Prepare Fresh": "आम्ही ताजे तयार करतो",
    "Made to order daily, no preservatives": "दररोज ऑर्डरनुसार बनवले जाणारे, परिरक्षक विरहित",
    "6–8 AM and 6–8 PM across Nashik": "संपूर्ण नाशिकमध्ये सकाळी 6-8 आणि संध्याकाळी 6-8",
    "Eat Healthy": "निरोगी खा",
    "Enjoy fresh, vegetarian, guilt-free food": "ताज्या, शाकाहारी आहाराचा आनंद घ्या",

    // Plans
    "Subscription Programs": "सदस्यता कार्यक्रम",
    "Follow Your Diet With Us": "आमच्यासोबत आपल्या आहाराचे पालन करा",
    "We offer 6-day and 25-day subscriptions, plus a single serving trial so you can try before you subscribe.": "आम्ही 6-दिवस आणि 25-दिवसांची सदस्यता ऑफर करतो, सोबतच एक ट्रायल देखील जेणेकरून तुम्ही सबस्क्रिप्शन घेण्यापूर्वी पाहू शकता.",
    "Choose from a 1-day trust builder, 6-day wellness plan, or our full 25-day transformation subscription. Fresh deliveries every morning and evening.": "1-दिवसाच्या ट्रस्ट बिल्डर, 6-दिवसांच्या वेलनेस प्लॅन किंवा आमच्या संपूर्ण 25-दिवसांच्या सबस्क्रिप्शनमधून निवडा. रोज सकाळी आणि संध्याकाळी ताजी डिलिव्हरी.",
    "Morning Slot": "सकाळची वेळ",
    "Evening Slot": "संध्याकाळची वेळ",
    "Morning Slot: ": "सकाळची वेळ: ",
    "Evening Slot: ": "संध्याकाळची वेळ: ",
    "Single Serving Trial": "सिंगल सर्विंग ट्रायल",
    "Try before you subscribe": "सदस्यता घेण्यापूर्वी आत्ताच वापरून पहा",
    "No commitment": "कोणतीही बांधिलकी नाही",
    "One-time order": "एक वेळची ऑर्डर",
    "Any juice or salad": "कोणताही ज्यूस किंवा सलाड",
    "Order via WhatsApp": "व्हाट्सएपद्वारे ऑर्डर करा",
    "6 Days Subscription": "6 दिवसांची सदस्यता",
    "A week of goodness": "एक आठवड्याचा चांगुलपणा",
    "Great for beginners": "सुरुवात करणाऱ्यांसाठी उत्तम",
    "Daily fresh delivery": "रोज ताजी डिलिव्हरी",
    "Choice of juices/salads": "ज्यूस/सलाडचा पर्याय",
    "Doorstep delivery": "दारापर्यंत डिलिव्हरी",
    "25 Days Subscription": "25 दिवसांची सदस्यता",
    "Full month transformation": "पूर्ण महिन्याचा बदल",
    "Best value": "सर्वोत्तम मूल्य",
    "Customizable diet plan": "कस्टमाईज करता येणारा डाइट प्लॅन",
    "Priority doorstep delivery": "प्राधान्याने होम डिलिव्हरी",
    "1 Day": "1 दिवस",
    "6 Days": "6 दिवस",
    "25 Days": "25 दिवस",
    "Single day serving": "एका दिवसाची सर्विंग",
    "Juice or Salad of your choice": "तुमच्या आवडीचा ज्यूस किंवा सलाड",
    "200ml / 300ml / 500ml (Juice)": "200 मिली / 300 मिली / 500 मिली (ज्यूस)",
    "200gm / 450gm (Salad)": "200 ग्रॅम / 450 ग्रॅम (सलाड)",
    "Morning (6–9 am) or Evening (5–7 pm)": "सकाळी (6-9) किंवा संध्याकाळी (5-7)",
    "6 consecutive days": "सलग 6 दिवस",
    "Juice + Salad combos available": "ज्यूस + सलाड कॉम्बो उपलब्ध",
    "25 days of daily wellness": "25 दिवसांचे दैनिक आरोग्य",
    "Single or combo products": "सिंगल किंवा कॉम्बो उत्पादने",

    // Products
    "All subscription-based products are available in Weekly and Monthly packages.": "सर्व सदस्यता-आधारित उत्पादने साप्ताहिक आणि मासिक पॅकेजेसमध्ये उपलब्ध आहेत.",
    "Carrot Juice": "गाजर ज्यूस",
    "Amla Juice": "आवळा ज्यूस",
    "Green Juice": "ग्रीन ज्यूस",
    "Mix Juice": "मिक्स ज्यूस",
    "Watermelon Juice": "कलिंगड ज्यूस",
    "Sugarcane Juice": "उसाचा रस",
    "Beetroot Juice": "बीट ज्यूस",
    "Combination Juice": "कॉम्बिनेशन ज्यूस",
    "Red Juice": "रेड ज्यूस",
    "Salad Meal": "सलाड जेवण",
    "Fruit Cuts": "कॅप केलेले फळे",
    "Salad Bowl": "सलाड बाऊल",
    "Sprout Salad": "मटकी/मूग सलाड",
    "Super Laddu": "सुपर लाडू",
    "Cold Pressed Oil": "लाकडी घाण्याचे तेल",
    "Super Dry Fruits Laddu": "सुपर ड्राय फ्रूट्स लाडू",

    // FAQ
    "Frequently Asked Questions": "वारंवार विचारले जाणारे प्रश्न",
    "Have more questions? Ask AI": "अधिक प्रश्न आहेत? एआय ला विचारा",
    "What is YOGYAHAR and what do you offer?": "योग्याहार काय आहे आणि तुम्ही काय ऑफर करता?",
    "YOGYAHAR is Nashik's trusted diet food brand offering fresh, natural, hygienic, tasty, and authentic ready-to-eat meals, salads, and juices.": "योग्याहार हा नाशिकचा विश्वासू डाएट फूड ब्रँड आहे जो ताजे, नैसर्गिक, स्वच्छ, चवदार आणि अस्सल रेडी-टू-ईट जेवण, सलाड आणि ज्यूस प्रदान करतो.",
    "Are your meals and juices really fresh and preservative-free?": "तुमचे जेवण आणि ज्यूस खरोखर ताजे आणि परिरक्षक विरहित आहेत का?",
    "Absolutely, every made-to-order YOGYAHAR meal and juice is prepared fresh daily using natural ingredients. No preservatives, no artificial colors, and no added sugar.": "नक्कीच, प्रत्येक योग्याहार जेवण आणि ज्यूस नैसर्गिक घटकांचा वापर करून दररोज ताजे तयार केले जातात. कोणतेही परिरक्षक नाही, कोणतेही कृत्रिम रंग नाही आणि कोणतीही अतिरिक्त साखर नाही.",
    "What types of subscriptions do you offer?": "तुम्ही कोणत्या प्रकारची सबस्क्रिप्शन्स ऑफर करता?",
    "We offer 6 days and 25 days subscriptions. You can also order a single serving to try before starting your subscription.": "आम्ही 6 दिवस आणि 25 दिवसांची सदस्यता ऑफर करतो. सबस्क्रिप्शन सुरू करण्यापूर्वी तुम्ही एका वेळेचे जेवण देखील ऑर्डर करू शकता.",
    "What are your delivery hours?": "तुमची डिलिव्हरीची वेळ काय आहे?",
    "We deliver daily from 6:00 AM to 8:00 AM and 6 PM to 8 PM across Nashik City.": "आम्ही संपूर्ण नाशिक शहरात दररोज सकाळी 6:00 ते 8:00 आणि संध्याकाळी 6 ते 8 या वेळेत डिलिव्हरी करतो.",
    "What payment methods do you accept?": "तुम्ही पेमेंटच्या कोणत्या पद्धती स्वीकारता?",
    "We accept UPI, Cash, and secure online payment links.": "आम्ही यूपीआय (UPI), रोख रक्कम आणि सुरक्षित ऑनलाइन पेमेंट लिंक्स स्वीकारतो.",
    "Do you provide non-veg salad?": "तुम्ही मांसाहारी सलाड देता का?",
    "No, YOGYAHAR purely focuses on vegetarian diet food.": "नाही, योग्याहार पूर्णपणे शाकाहारी आहारावर लक्ष केंद्रित करतो.",
    "Can I customize my meals?": "मी माझे जेवण कस्टमाईज करू शकतो का?",
    "Our meals are mainly pre-designed, but custom plans are possible via a WhatsApp request to +91 7499643234.": "आमचे जेवण प्रामुख्याने आधी डिझाइन केलेले आहे, परंतु +91 7499643234 वर व्हाट्सएपद्वारे विनंती केल्यास कस्टमाईज्ड प्लॅन्स शक्य आहेत.",

    // Newsletter
    "Never miss a single news": "एकही बातमी चुकवू नका",
    "Stay informed with updates on our products and services. Stay connected and follow your diet with us!": "आमच्या उत्पादनांच्या आणि सेवांच्या अपडेट्ससह माहिती मिळवा. संपर्कात राहा आणि आमच्यासोबत आहाराचे पालन करा!",
    "📩 Stay Updated with YOGYAHAR": "📩 योग्याहार सोबत अपडेट राहा",
    "Subscribe to our newsletter for the latest updates, offers & health tips.": "नवीनतम अपडेट्स, ऑफर्स आणि आरोग्य टिप्ससाठी आमच्या न्यूजलेटरचे सदस्य व्हा.",
    "Enter your email address": "तुमचा ईमेल पत्ता प्रविष्ट करा",
    "Subscribe": "सदस्य व्हा",

    // Footer
    "Quick Links": "जलद लिंक्स",
    "Nashik's trusted diet food brand since 2018. Follow Your Diet With Us — fresh, natural, hygienic, vegetarian meals, salads and juices, delivered to your doorstep.": "2018 पासून नाशिकचा विश्वासू डाएट फूड ब्रँड. आमच्यासोबत तुमच्या आहाराचे पालन करा - ताजे, नैसर्गिक, स्वच्छ, शाकाहारी जेवण, सलाड आणि ज्यूस, तुमच्या दारापर्यंत पोहोचवले जातात.",
    "🕐 6–8 AM & 6–8 PM daily": "🕐 दररोज सकाळी 6–8 आणि संध्याकाळी 6–8",
    "📍 Nashik, Maharashtra, India": "📍 नाशिक, महाराष्ट्र, भारत",
    "© 2025 YOGYAHAR All Rights Reserved.": "© 2025 योग्याहार सर्व हक्क राखीव.",
    "Follow Your Diet With Us!": "आमच्यासोबत आहाराचे पालन करा!",

    // Standalone: Contact Us
    "We'd Love to Hear From You!": "आम्हाला तुमच्याकडून ऐकायला आवडेल!",
    "Have a question, feedback, or just want to say hello? We're here for you. Reach out to us and we'll get back to you as soon as possible.": "काही प्रश्न, अभिप्राय आहे की फक्त नमस्कार करायचा आहे? आम्ही तुमच्यासाठी येथे आहोत. आमच्याशी संपर्क साधा आणि आम्ही लवकरात लवकर तुमच्याशी संपर्क साधू.",
    "Our Location": "आमचे ठिकाण",
    "Call Us": "आम्हाला कॉल करा",
    "Email Us": "आम्हाला ईमेल करा",
    "Working Hours": "कामाचे तास",
    "Send Us a Message": "आम्हाला मेसेज पाठवा",
    "We'll respond to your inquiry as soon as possible.": "आम्ही तुमच्या चौकशीला लवकरात लवकर प्रतिसाद देऊ.",
    "Your Name": "तुमचे नाव",
    "Email Address": "ईमेल पत्ता",
    "Phone Number": "फोन नंबर",
    "Subject": "विषय",
    "Your Message": "तुमचा संदेश",
    "Send Message": "संदेश पाठवा",
    "Thank you!": "धन्यवाद!",
    "Your message has been sent successfully.": "तुमचा संदेश यशस्वीरित्या पाठवला गेला आहे.",

    // Standalone: About Us page
    "Providing Wholesome Diet Nutrition Since 2018": "2018 पासून उत्तम डाएट पोषण प्रदान करत आहोत",
    "Welcome to our standalone About page! We make fresh, natural, hygienic, tasty, authentic diet food. We believe in selling Taste, Time, Knowledge, Variety, and Consistency.": "आमच्या स्वतंत्र अबाउट पेजवर आपले स्वागत आहे! आम्ही ताजे, नैसर्गिक, स्वच्छ, चवदार, अस्सल डाएट फूड बनवतो. आमचा चव, वेळ, ज्ञान, विविधता आणि सुसंगतता विकण्यावर विश्वास आहे.",
    "\"Nourishing your body with local healthy products, delivered fresh daily.\"": "\"स्थानिक आरोग्यदायी उत्पादनांनी शरीराला पोषण द्या, रोज ताजे मिळवा.\"",
    "Ready To Start Your": "सुरू करण्यास तयार आहात का तुमची",
    "Health Journey?": "आरोग्य यात्रा?",
    "Join thousands of happy customers who trust YOGYAHAR to fuel their body and nourish their life.": "त्या हजारो आनंदी ग्राहकांमध्ये सामील व्हा जे त्यांच्या शरीराला ऊर्जा देण्यासाठी आणि जीवनाचे पोषण करण्यासाठी योग्याहार वर विश्वास ठेवतात.",

    // Standalone: Services
    "Tailored Plans for Your Health Goals": "तुमच्या आरोग्य ध्येयांसाठी तयार केलेले प्लॅन्स",
    "We deliver delicious, portion-controlled diet food across Nashik to fit your lifestyle.": "आम्ही तुमच्या जीवनशैलीला साजेसे नासिकमध्ये चवदार, नियंत्रित डाएट फूड वितरित करतो.",
    "Office Professionals": "कार्यालयीन कर्मचारी",
    "Gym & Fitness Lovers": "जिम आणि फिटनेस प्रेमी",
    "Weight Loss Followers": "वजन कमी करू इच्छिणारे",
    "Family & Seniors": "कुटुंब आणि ज्येष्ठ नागरिक",
    "Fuel your productive workdays with Yogyahar's desk-friendly meal plans. Convenient, nourishing, and delivered fresh to help corporate professionals maintain peak focus without the midday slump.": "योग्याहारच्या जेवण योजनेद्वारे तुमचे कार्यालयीन कामाचे दिवस अधिक उत्साही बनवा. सोयीस्कर, पौष्टिक आणि दुपारी येणारा आळस टाळण्यास मदत करण्यासाठी कॉर्पोरेट कर्मचाऱ्यांना ताजे वितरित केले जाते.",
    "Support your active lifestyle and workout recovery with Yogyahar's high-protein bowls and clean energy snacks. Carefully portioned and nutrient-dense fuel designed specifically for fitness enthusiasts.": "योग्याहारच्या उच्च-प्रथिनेयुक्त वाडगा (बाऊल) आणि शुद्ध ऊर्जा स्नॅक्ससह आपल्या सक्रिय जीवनशैलीचे आणि व्यायामाचे समर्थन करा. फिटनेस प्रेमींसाठी काळजीपूर्वक डिझाइन केलेले आणि पौष्टिक अन्न.",
    "Reach your weight management goals naturally with Yogyahar's low-calorie, high-fiber salads and detox programs. Enjoy calorie-conscious portions that are incredibly satisfying and delicious.": "योग्याहारच्या कमी उष्मांक, उच्च फायबर सलाड आणि डिटॉक्स कार्यक्रमांद्वारे आपले वजन नियंत्रित करा. अत्यंत समाधानकारक आणि चवदार अन्नाचा आनंद घ्या.",
    "Bring wholesome nutrition to your dinner table. Yogyahar provides easy-to-digest, vitamin-rich fruit and veggie selections crafted to promote longevity, health, and vitality for your entire family.": "तुमच्या जेवणाच्या टेबलावर पौष्टिक आहार आणा. योग्याहार तुमच्या संपूर्ण कुटुंबाचे आरोग्य आणि दीर्घायुष्य वाढवण्यासाठी सहज पचणारे, जीवनसत्त्वयुक्त फळे आणि भाज्यांचे पर्याय देतो.",
    "Customize & Schedule": "कस्टमाईज आणि नियोजित करा",
    "Fresh Daily Delivery": "दररोज ताजी डिलिव्हरी",
    "Our team prepares your meals fresh every morning and delivers them cold to your doorstep.": "आमची टीम रोज सकाळी ताजे जेवण बनवून तुमच्या दारापर्यंत थंड डिलिव्हरी करते.",

    // New additions for products and sections
    "Rasahar · Juices · Subscription-based": "रासाहार · ज्यूस · सबस्क्रिप्शन-आधारित",
    "Regular, Seasonal & Special Juices": "नियमित, हंगामी आणि विशेष ज्यूस",
    "throughout the year": "वर्षभर उपलब्ध",
    "available during the season": "हंगामात उपलब्ध",
    "particular months only": "फक्त विशिष्ट महिन्यांत",
    "Get Your Paid One-Day Trial!": "तुमचा सशुल्क एक-दिवसीय ट्रायल मिळवा!",
    "Start Your Juice Monthly Subscription Today!": "आजच तुमचे ज्यूसचे मासिक सबस्क्रिप्शन सुरू करा!",
    "6 Days, 6 Flavors": "6 दिवस, 6 फ्लेवर्स",
    "Metabolism & Toxins Flush": "चयापचय क्रिया वाढवणे आणि विषारी पदार्थ बाहेर टाकणे",
    "100% Organic & Fresh Daily": "100% सेंद्रिय आणि दररोज ताजे",
    "No Added Sugar & Preservatives": "अतिरिक्त साखर आणि परिरक्षक विरहित",
    "Premium Glass Bottle Delivery": "प्रीमियम काचेच्या बाटलीमध्ये डिलिव्हरी",
    "Pause/Resume Plans Easily": "योजना सहजपणे थांबवा (Pause) किंवा पुन्हा सुरू करा (Resume)",
    "Salad · Subscription-based": "सलाद · सबस्क्रिप्शन-आधारित",
    "Salad Meal, Bowl, Sprouts & Fruit Cuts": "सलाड जेवण, बाऊल, मटकी/मूग आणि कापलेली फळे",
    "Fresh, premium subscription salads delivered daily. Made with crisp organic greens, nutrient-dense sprouts, fresh fruit cuts, and high-protein ingredients to keep you healthy every day.": "दररोज वितरित केले जाणारे ताजे, प्रीमियम सबस्क्रिप्शन सलाड. तुम्हाला निरोगी ठेवण्यासाठी सेंद्रिय पालेभाज्या, पोषक तत्वांनी युक्त मोड आलेले कडधान्य, ताजी कापलेली फळे आणि उच्च प्रथिनेयुक्त घटकांपासून बनवलेले.",
    "Get Your One-Day Trial!": "तुमचा एक-दिवसीय ट्रायल मिळवा!",
    "Start Your Salad's Monthly Subscription Today!": "आजच तुमचे सलाडचे मासिक सबस्क्रिप्शन सुरू करा!",
    "Non-Subscription Essentials": "नॉन-सबस्क्रिप्शन आवश्यक उत्पादने",
    "Pure & Traditional Wellness Treats": "शुद्ध आणि पारंपारिक निरोगी उत्पादने",
    "Explore our hand-crafted, daily essentials. Made using traditional, clean methods with zero preservatives to nourish your body and soul.": "आमच्या हस्तनिर्मित, दैनंदिन आवश्यक उत्पादनांचा शोध घ्या. तुमच्या शरीराला आणि आत्म्याला पोषण देण्यासाठी कोणत्याही परिरक्षकांशिवाय पारंपारिक, स्वच्छ पद्धतींचा वापर करून बनवलेले.",

    // Testimonials and additional Detox items
    "Detox Water": "डिटॉक्स वॉटर",
    "Purify your body with our premium range of daily detox infusions. Handcrafted with fresh citrus fruits, cooling cucumber, and organic herbs to keep you hydrated and active all day long.": "आमच्या प्रीमियम डेली डिटॉक्स ड्रिंक्ससह आपले शरीर शुद्ध करा. तुम्हाला दिवसभर हायड्रेटेड आणि सक्रिय ठेवण्यासाठी ताजी लिंबूवर्गीय फळे, थंड काकडी आणि सेंद्रिय औषधी वनस्पतींपासून बनवलेले.",
    "What Our Customers Say": "आमचे ग्राहक काय म्हणतात",
    "Real People. Real Results.": "खरे लोक. खरे निकाल.",
    "Discover how YOGYAHAR is helping people across Nashik transform their health journey with daily fresh, natural, and preservative-free meals and juices.": "दररोज ताजे, नैसर्गिक आणि परिरक्षक विरहित जेवण आणि ज्यूसच्या माध्यमातून योग्याहार नाशिकमधील लोकांना त्यांच्या आरोग्याचा प्रवास बदलण्यास कशी मदत करत आहे ते शोधा.",
    "Yogyahar's juices make me feel fresh and rejuvenated every day — sugar-free and remarkably consistent service.": "योग्याहारचे ज्यूस मला दररोज ताजेतवाने आणि टवटवीत बनवतात - साखर-मुक्त आणि उत्कृष्ट सातत्यपूर्ण सेवा.",
    "A promising start-up known for excellent service and timely delivery, every single day.": "उत्कृष्ट सेवा आणि वेळेवर डिलिव्हरीसाठी ओळखले जाणारे एक उत्कृष्ट स्टार्ट-अप, दररोज.",
    "Their morning delivery of health-promoting juice has genuinely become a part of my healthy routine.": "आरोग्य वाढवणाऱ्या ज्यूसची त्यांची सकाळची डिलिव्हरी खरोखरच माझ्या निरोगी दिनचर्याचा एक भाग बनली आहे.",
    "Refreshed and fantastic! My 30-day juice cleanse with Yogyahar was a great experience.": "टवटवीत आणि विलक्षण! योग्याहारसोबतचा माझा ३० दिवसांचा ज्यूस डिटॉक्स एक उत्तम अनुभव होता.",
    "Dentist": "दंत चिकित्सक",
    "Civil Engineer": "सिव्हिल इंजिनिअर",
    "Banker": "बँकर",
    "Advisory System Analyst": "सल्लागार प्रणाली विश्लेषक",
    "Throughout the year": "वर्षभर उपलब्ध",
    "Yes": "होय",
    "No": "नाही",
    "A refreshing blend of premium local ingredients. Designed to detox your body, improve digestion, and boost your energy levels naturally.": "प्रीमियम स्थानिक घटकांचे एक ताजेतवाने मिश्रण. तुमच्या शरीराला डिटॉक्स करण्यासाठी, पचन सुधारण्यासाठी आणि नैसर्गिकरित्या तुमची ऊर्जा पातळी वाढवण्यासाठी डिझाइन केलेले.",
    "In recent years, cold-pressed juices have evolved from a trendy health wellness routine into a scientifically-proven nutritional staple. But what makes cold-pressed juicing fundamentally superior to traditional centrifugal juicers?": "अलिकडच्या वर्षांत, कोल्ड-प्रेस्ड ज्यूस हे केवळ एक फॅशनेबल वेलनेस रूटीन न राहता एक वैज्ञानिकदृष्ट्या सिद्ध झालेले आरोग्यदायी अन्न बनले आहे. पण कोल्ड-प्रेस्ड ज्युसिंग पारंपारिक ज्युसरपेक्षा नक्की कसे श्रेष्ठ ठरते?",
    "The Science Behind Cold-Pressed Hydraulic Extraction": "कोल्ड-प्रेस्ड हायड्रॉलिक एक्स्ट्रॅक्शनमागील विज्ञान",
    "Unlike traditional high-speed juicers whose spinning blades create heat friction and drag massive amounts of air into the liquid—causing rapid oxidation and heat degradation of delicate vitamins—cold-pressed hydraulic extraction gently presses fresh fruits and vegetables under tons of pressure without heat exposure.": "पारंपारिक हाय-स्पीड ज्युसरच्या फिरत्या ब्लेडमुळे उष्णता निर्माण होते आणि हवेचा संपर्क येतो, ज्यामुळे नाजूक जीवनसत्त्वे नष्ट होतात. याउलट, कोल्ड-प्रेस्ड हायड्रॉलिक एक्स्ट्रॅक्शन कोणत्याही उष्णतेशिवाय टनांच्या दाबाखाली फळे आणि भाज्यांचा रस हळूवारपणे पिळून काढते.",
    "Key Health Benefits of Daily Juicing": "रोज ज्यूस पिण्याचे मुख्य आरोग्य फायदे",
    "Maximum Bioavailability:": "कमाल पोषण उपलब्धता:",
    "Retains up to 3x more vitamins A, C, E, and plant antioxidants.": "३ पटीने जास्त जीवनसत्त्वे ए, सी, ई आणि वनस्पती अँटिऑक्सिडंन्टस टिकवून ठेवते.",
    "Cellular Absorption:": "पेशींद्वारे शोषण:",
    "Allows your digestive system a resting window while delivering instant hydration directly into your bloodstream.": "थेट तुमच्या रक्तप्रवाहात झटपट पोषण पोहोचवून तुमच्या पचनसंस्थेला विश्रांतीचा वेळ मिळवून देते.",
    "100% Pure:": "१००% शुद्ध:",
    "No added refined sugar, artificial flavors, preservatives, or diluting concentrates.": "कोणतीही साखर, कृत्रिम फ्लेवर, परिरक्षक किंवा पाण्याचे मिश्रण नाही.",
    "How to Integrate Cold-Pressed Juices into Your Life": "कोल्ड-प्रेस्ड ज्यूस तुमच्या दिनचर्येत कसे समाविष्ट करावे",
    "We recommend enjoying a 300ml bottle of fresh <em>Carrot-Beet-Ginger</em> or <em>Amla Green Juice</em> every morning on an empty stomach to kickstart your metabolism and boost immunity.": "तुमची चयापचय क्रिया आणि रोगप्रतिकारक शक्ती वाढवण्यासाठी आम्ही दररोज सकाळी रिकाम्या पोटी ३०० मिली ताजे <em>गाजर-बीट-आले</em> किंवा <em>आंवला ग्रीन ज्यूस</em> पिण्याची शिफारस करतो.",
    "Sustainable weight loss isn't about restrictive starvation; it's about supplying high-density micro-nutrients that satisfy your body's cellular hunger and stabilize energy.": "शाश्वत वजन कमी करणे म्हणजे स्वतःला उपाशी ठेवणे नव्हे; तर शरीराची भूक शमवणारी आणि ऊर्जा टिकवून ठेवणारी उच्च-घनतेची सूक्ष्म पोषक तत्वे पुरवणे होय.",
    "Anatomy of a High-Protein Salad Meal": "उच्च-प्रथिनयुक्त (हाय-प्रोटिन) सलाड जेवणाची रचना",
    "Combining sprouted grains, crisp seasonal greens, and cold-pressed seeds provides a complete amino-acid profile while offering rich dietary fiber.": "मोड आलेले कडधान्य, कुरकुरीत हंगामी पालेभाज्या आणि लाकडी घाण्याचे तेल/बिया यांचे संयोजन संपूर्ण अमिनो-अॅसिड प्रोफाइल आणि मुबलक फायबर प्रदान करते.",
    "Key Ingredients for Satiety": "पोट भरलेले ठेवण्यासाठी मुख्य घटक",
    "Sprouted Mung & Chickpeas:": "मोड आलेले मूग आणि चणे:",
    "High-protein, easily digestible bio-active nutrients.": "उच्च प्रथिने आणि सहज पचणारे जैविक सक्रिय पोषक घटक.",
    "Walnuts & Pumpkin Seeds:": "अक्रोड आणि भोपळ्याच्या बिया:",
    "Healthy Omega-3 fats for brain clarity and heart health.": "मेंदूची स्पष्टता आणि हृदयाच्या आरोग्यासाठी निरोगी ओमेगा -३ फॅट्स.",
    "Raw Leafy Greens:": "कच्च्या पालेभाज्या:",
    "Loaded with natural chlorophyl and essential minerals.": "नैसर्गिक क्लोरोफिल आणि आवश्यक खनिजांनी भरपूर.",
    "In Ayurveda, a strong <em>Agni</em> (digestive fire) is considered the cornerstone of physical longevity, clear skin, and vibrant mental clarity. Without balanced digestion, even the healthiest foods cannot be fully assimilated by the body's tissues.": "आयुर्वेदात, उत्तम <em>अग्नी</em> (पाचक अग्नी) हा दीर्घायुष्य, स्वच्छ त्वचा आणि मानसिक स्पष्टतेचा पाया मानला जातो. पचनक्रिया संतुलित नसल्यास, सकस अन्नही शरीराला पूर्णपणे शोषून घेता येत नाही.",
    "Understanding Agni: The Centerpiece of Health": "अग्नी समजून घेणे: आरोग्याचा केंद्रबिंदू",
    "According to the classical text <em>Charak Samhita</em>, Agni governs not just digestion but also our internal heat, cellular intelligence, and mental energy. When Agni is weak (Mandagni), it creates a toxic metabolic byproduct known as <strong>Ama</strong>, which is the root cause of chronic sluggishness and physical discomfort.": "अभिजात ग्रंथ <em>चरक संहिता</em> नुसार, अग्नी केवळ पचनच नाही तर आपली अंतर्गत उष्णता, कोशिकीय बुद्धिमत्ता आणि मानसिक ऊर्जा देखील नियंत्रित करतो. जेव्हा अग्नी मंद असतो (मंदाग्नी), तेव्हा तो <strong>आम (Ama)</strong> नावाचे विषारी द्रव्य तयार करतो, जे दीर्घकालीन थकवा आणि शारीरिक त्रासाचे मुख्य कारण आहे.",
    "5 Habits to Practice Daily": "दररोज आचरणात आणायच्या ५ सवयी",
    "Copper Vessel Water:": "तांब्याच्या भांड्यातील पाणी:",
    "Hydrate with copper-infused water (Tamra Jal) first thing in the morning to balance all three Doshas (Vata, Pitta, and Kapha).": "सर्व तीन दोष (वात, पित्त आणि कफ) संतुलित करण्यासाठी सकाळी उठल्याबरोबर तांब्याच्या पाण्याचे (ताम्र जल) सेवन करा.",
    "Eat Fresh & Seasonal:": "ताजे आणि हंगामी खा:",
    "Align your dietary choices with seasonal fruits and vegetables to keep your gut microbiome resilient.": "तुमचा जठराग्नी निरोगी ठेवण्यासाठी हंगामी फळे आणि भाज्यांचा आहारात समावेश करा.",
    "Main Meal at Midday:": "दुपारचे मुख्य जेवण:",
    "Eat your largest meal when Agni is naturally strongest at noon, matching the highest position of the sun.": "जेव्हा अग्नी नैसर्गिकरित्या दुपारी सर्वात जास्त तीव्र असतो (सूर्याच्या सर्वोच्च स्थितीनुसार), तेव्हा तुमचे सर्वात मोठे जेवण घ्या.",
    "Mindful Chewing:": "जाणीवपूर्वक चावणे:",
    "Chew each bite thoroughly to initiate salivary digestive enzymes and prevent bloating.": "लाळ निर्मिती वाढवून अन्न पचन सुधारण्यासाठी आणि गॅस टाळण्यासाठी प्रत्येक घास नीट चावून खा.",
    "Early Dinner Window:": "लवकर रात्रीचे जेवण:",
    "Finish dinner early (before 8 PM) to allow complete cellular healing and detoxification overnight.": "रात्री शरीराच्या नैसर्गिक डिटॉक्सिफिकेशन आणि उपचारांसाठी censure तुमचे रात्रीचे जेवण लवकर (रात्री ८ च्या आधी) पूर्ण करा.",
    "Healthy Routine Planning": "निरोगी दिनचर्या नियोजन",
    "To transition into an Ayurvedic schedule, begin by drinking warm water with lemon and ginger slices in the morning to stimulate peristalsis. Next, replace heavy cold breakfasts with warm, freshly cooked grains or hot herbal teas. By respecting your body's circadian rhythm, you will experience natural weight regulation and sustained mental clarity throughout the day.": "आयुर्वेदिक दिनचर्येमध्ये बदल करण्यासाठी, सकाळी लिंबू आणि आल्याच्या तुकड्यांसह कोमट पाणी पिण्यास सुरवात करा. यानंतर, जड आणि थंड नाश्त्याऐवजी कोमट, ताजे शिजवलेले अन्न किंवा गरम हर्बल चहा घ्या. तुमच्या शरीराच्या नैसर्गिक चक्राचा आदर केल्याने नैसर्गिकरित्या वजन नियंत्रित होईल आणि मानसिक स्पष्टता टिकून राहील.",
    "Mid-afternoon energy crashes often drive us toward processed sugary snacks. Yogyahar Super Laddus are handcrafted to deliver sustained vitality with zero guilt.": "दुपारच्या वेळी येणाऱ्या थकव्यामुळे आपण अनेकदा साखरयुक्त प्रक्रिया केलेले स्नॅक्स खातो. योग्याहार सुपर लाडू कोणत्याही पश्चात्तापाशिवाय शाश्वत ऊर्जा देण्यासाठी हस्तनिर्मित आहेत.",
    "Combating Midday Fatigue Naturally": "दुपारच्या थकव्यावर नैसर्गिकरित्या मात करा",
    "For most corporate professionals and active individuals, 4:00 PM is a challenging hour. Traditional options like caffeine, refined sugar cookies, and fried snacks cause quick insulin spikes followed by rapid exhaustion. Super Laddus solve this problem by leveraging complex plant-based carbohydrates and healthy fats that release energy slowly into your bloodstream.": "बहुतेक नोकरदार वर्गासाठी आणि सक्रिय लोकांसाठी, दुपारी ४ वाजताची वेळ थकवणारी असते. कॅफिन, रिफाइंड साखरेची बिस्किटे आणि तळलेले पदार्थ झटपट ऊर्जा देतात पण नंतर लगेच थकवा आणतात. सुपर लाडू शरीरात हळूहळू ऊर्जा सोडणारे निरोगी फॅट्स आणि जटिल कर्बोदके वापरून ही समस्या सोडवतात.",
    "Nutritional Profile: What's Inside?": "पोषण मूल्य: आत काय आहे?",
    "Each Yogyahar Super Laddu is a compact power cell containing:": "प्रत्येक योग्याहार सुपर लाडूमध्ये खालील घटक समाविष्ट आहेत:",
    "Premium Dry Fruits:": "प्रीमियम सुका मेवा:",
    "Walnuts, almonds, and cashews packed with minerals.": "खनिजांनी समृद्ध असलेले अक्रोड, बदाम आणि काजू.",
    "Organic Seed Blend:": "सेंद्रिय बियांचे मिश्रण:",
    "Pumpkin seeds, flaxseeds, and sunflower seeds containing rich Omega-3 fatty acids.": "ओमेगा-३ फॅटी अॅसिडने समृद्ध असलेल्या भोपळ्याच्या बिया, अळशी आणि सूर्यफुलाच्या बिया.",
    "Natural Sweeteners:": "नैसर्गिक गोडवा:",
    "Dates and raw figs with no refined cane sugar.": "कोणतीही रिफाइंड साखर नसलेले खजूर आणि सुके अंजीर.",
    "Local Wood-Pressed Ghee:": "लाकडी घाण्याचे तूप:",
    "Promotes lubricating joints and supports absorption of fat-soluble vitamins.": "सांधे निरोगी ठेवण्यास मदत करते आणि जीवनसत्त्वांचे शोषण वाढवते.",
    "Fresh Doorstep Delivery": "ताजी घरपोच डिलिव्हरी",
    "Prepared in small batches under hygienic conditions, our laddus are delivered directly across Nashik so you always have a pack of healthy fuel ready at your desk or home pantry.": "स्वच्छ वातावरणात लहान बॅचेसमध्ये तयार केलेले, आमचे लाडू थेट संपूर्ण नाशिकमध्ये वितरित केले जातात जेणेकरून तुमच्याकडे ऑफिसमध्ये किंवा घरी नेहमी निरोगी उर्जा उपलब्ध असेल.",

    // About Page (mr)
    "ABOUT STANDALONE PAGE": "माहिती पृष्ठ",
    "About Yogyahar": "योग्याहारबद्दल",
    "Nourishing Nashik\nWith Pure Health": "शुद्ध आरोग्यासह\nनाशिकचे पोषण",
    "Providing Wholesome Diet Nutrition Since 2018": "२०१८ पासून उत्तम डाएट पोषण प्रदान करत आहोत",
    "Welcome to our standalone About page! We make fresh, natural, hygienic, tasty, authentic diet food. We believe in selling Taste, Time, Knowledge, Variety, and Consistency.": "आमच्या माहिती पृष्ठावर आपले स्वागत आहे! आम्ही ताजे, नैसर्गिक, स्वच्छ, चवदार, अस्सल डाएट फूड बनवतो. आम्ही चव, वेळ, ज्ञान, विविधता आणि सातत्य यावर विश्वास ठेवतो.",
    "Discover Yogyahar's fresh daily salads, cold-pressed juices, and healthy subscriptions prepared from raw, natural ingredients.": "कच्च्या, नैसर्गिक घटकांपासून बनवलेले योग्याहारचे दररोजचे ताजे सलाड, कोल्ड-प्रेस्ड ज्यूस आणि निरोगी सबस्क्रिप्शन शोधा.",
    "\"Nourishing your body with local healthy products, delivered fresh daily.\"": "\"स्थानिक आरोग्यदायी उत्पादनांनी शरीराला पोषण द्या, रोज ताजे मिळवा.\"",
    "What We Do": "आम्ही काय करतो",
    "At Yogyahar, we prepare 100% fresh fruit salads, sprout salads, vegetable salads, cold-pressed juices, smoothies, and peel-cut fruits all crafted daily with premium quality ingredients. Our aim is to make healthy eating easy, tasty, and convenient for everyone.": "योग्याहारमध्ये, आम्ही दररोज प्रीमियम दर्जाच्या घटकांपासून १००% ताजे फळांचे सलाड, मटकीचे सलाड, भाजीचे सलाड, कोल्ड-प्रेस्ड ज्यूस, स्मूदी आणि कापलेली फळे तयार करतो. प्रत्येकासाठी पौष्टिक आहार सोपा, चवदार आणि सोयीस्कर बनवणे हे आमचे उद्दिष्ट आहे.",
    "Why We Started": "आम्ही का सुरू केले",
    "Yogyahar was founded with a simple mission: to make healthy living effortless for busy people. We realized many want to eat clean but do not have time to wash, peel, or cut fruits every day. So we created a service delivering fresh, preservative-free salads directly to your doorstep.": "व्यग्र लोकांसाठी निरोगी जीवन सोपे करणे या एका साध्या उद्देशाने योग्याहारची स्थापना झाली. आम्हाला जाणवले की अनेकांना पौष्टिक खायचे असते पण रोज फळे धुण्यासाठी, सोलण्यासाठी किंवा कापण्यासाठी वेळ नसतो. म्हणून आम्ही थेट तुमच्या दारापर्यंत ताजे, परिरक्षक विरहित सलाड पोहोचवणारी सेवा सुरू केली.",
    "Delivered with Care": "काळजीपूर्वक वितरित",
    "Every bowl is prepared in a hygienic kitchen, packed in eco-friendly biodegradable packaging, and delivered with care. We ensure that you receive nature's best – fresh, safe, and ready to enjoy directly at your home or workplace.": "प्रत्येक बाउल एका स्वच्छ स्वयंपाकघरात तयार केला जातो, पर्यावरणपूरक बायोडिग्रेडेबल पॅकेजिंगमध्ये पॅक केला जातो आणि काळजीपूर्वक वितरित केला जातो. तुम्हाला निसर्गाचे सर्वोत्तम - ताजे, सुरक्षित आणि थेट तुमच्या घरी किंवा कामाच्या ठिकाणी आनंद घेण्यासाठी तयार अन्न मिळेल याची आम्ही खात्री देतो.",
    "Always Here to Help": "मदतीसाठी नेहमी तत्पर",
    "From daily subscription assistance to customized orders for events, we are always here for you. Each product is packed safely and quality-checked. If you ever need help, have a query, or require a replacement, reach us anytime through call or WhatsApp.": "दैनंदिन सबस्क्रिप्शन मदतीपासून ते कार्यक्रमांसाठी कस्टमाईज्ड ऑर्डर्सपर्यंत, आम्ही नेहमी तुमच्यासाठी येथे आहोत. प्रत्येक उत्पादन सुरक्षितपणे पॅक केले जाते आणि त्याची गुणवत्ता तपासली जाते. तुम्हाला कधीही मदत हवी असल्यास, शंका असल्यास किंवा बदली उत्पादन हवे असल्यास, कॉल किंवा व्हाट्सएपद्वारे कधीही संपर्क साधा.",
    "Seasonal mixed fruit salads": "हंगामी मिश्रित फळांचे सलाड",
    "Premium & exotic fruit bowls": "प्रीमियम आणि विदेशी फळांचे बाउल",
    "Nutritious sprout salads": "पौष्टिक मोड आलेले सलाड",
    "Fresh veg salads": "ताजे भाज्यांचे सलाड",
    "Cold-pressed juices & smoothies": "कोल्ड-प्रेस्ड ज्यूस आणि स्मूदी",
    "Custom corporate salad platters": "कस्टम कॉर्पोरेट सलाड प्लॅटर्स",
    "Welcome to Our Fruitful Journey": "आमच्या फलदायी प्रवासात आपले स्वागत आहे",
    "Yogyahar is a healthy food brand dedicated to delivering 100% fresh, hygienic, and preservative-free fruit salads and healthy meals right to your doorstep. We believe that healthy eating should be easy, affordable, and delicious for everyone.": "योग्याहार हा एक आरोग्यदायी खाद्य ब्रँड आहे जो १००% ताजे, स्वच्छ आणि परिरक्षक विरहित फळांचे सलाड आणि आरोग्यदायी जेवण थेट तुमच्या दारापर्यंत पोहोचवण्यासाठी समर्पित आहे. आमचा असा विश्वास आहे की निरोगी खाणे प्रत्येकासाठी सोपे, परवडणारे आणि चवदार असावे.",
    "We specialize in freshly prepared fruit salads, premium and exotic fruit bowls, sprout salads, vegetable salads, cold-pressed juices, smoothies, and peel-cut ready-to-eat fruits. Every order is prepared daily using premium-quality ingredients sourced from trusted suppliers.": "आम्ही ताजे तयार केलेले फळांचे सलाड, प्रीमियम आणि विदेशी फळांचे बाउल, मटकीचे सलाड, भाज्यांचे सलाड, कोल्ड-प्रेस्ड ज्यूस, स्मूदी आणि कापलेली फळे यामध्ये तज्ञ आहोत. प्रत्येक ऑर्डर विश्वासू पुरवठादारांकडून घेतलेल्या प्रीमियम दर्जाच्या घटकांचा वापर करून दररोज तयार केली जाते.",
    "Our Vision": "आमचा दृष्टिकोन",
    "Our Mission": "आमचे ध्येय",
    "Celebrate Freshness, Everyday": "दररोज ताजेपणा साजरा करा",
    "Discover nature's goodness with a wide range of:": "विविध प्रकारच्या अन्नपदार्थांसह निसर्गाच्या चांगुलपणाचा शोध घ्या:",
    "Freshness, taste, and farm-fresh quality are delivered to you with every order.": "प्रत्येक ऑर्डरसोबत ताजेपणा, चव आणि शेतातील ताजी गुणवत्ता तुमच्यापर्यंत पोहोचवली जाते.",
    "Order Now": "आत्ताच ऑर्डर करा",
    "Trending now": "सध्या ट्रेंडिंग",
    "Watermelon Juice": "टरबूज ज्यूस",
    "Fruit Cuts": "कापलेली फळे",
    "Detox Water": "डिटॉक्स वॉटर",
    "Super Laddu": "सुपर लाडू",
    "More Articles You Might Like": "तुम्हाला आवडणारे इतर लेख",
    "Read article": "लेख वाचा",
    "Why Cold-Pressed Juices Are Superior for Daily Detox & Energy": "दैनिक डिटॉक्स आणि ऊर्जेसाठी कोल्ड-प्रेस्ड ज्यूस का सर्वोत्तम आहेत",
    "Discover how cold-pressed extraction preserves vital living enzymes, vitamins, and antioxidants compared to conventional centrifugal blending.": "पारंपारिक सेंट्रीफ्यूगल ब्लेंडिंगच्या तुलनेत कोल्ड-प्रेस्ड पद्धत जीवनसत्त्वे, एन्झाइम्स आणि अँटिऑक्सिडंट्स कशी सुरक्षित ठेवते ते शोधा.",
    "The Power of High-Protein Salads in Sustainable Weight Loss": "शाश्वत वजन कमी करण्यासाठी हाय-प्रोटिन सलाडची ताकद",
    "Learn how pairing raw microgreens, sprouts, organic seeds, and plant proteins keeps you satisfied, regulates blood sugar, and boosts metabolism.": "कच्च्या मायक्रोग्रीन्स, मोड आलेले कडधान्य, सेंद्रिय बिया आणि वनस्पती प्रथिनांच्या सेवनाने पोट कसे भरलेले राहते आणि चयापचय वाढते ते शिका.",
    "5 Simple Ayurvedic Habits for Natural Digestion & High Energy": "नैसर्गिक पचन आणि उच्च ऊर्जेसाठी ५ सोप्या आयुर्वेदिक सवयी",
    "Integrate ancient Dinacharya wellness principles into modern daily schedules for improved Agni (digestive fire) and mental clarity.": "पचनक्रिया (अग्नी) आणि मानसिक स्पष्टता सुधारण्यासाठी प्राचीन दिनचर्या पद्धतींचा आधुनिक दिनक्रमात समावेश करा.",
    "Super Laddus: The Guilt-Free Energy Snack for Busy Professionals": "सुपर लाडू: व्यस्त लोकांसाठी एक आरोग्यदायी एनर्जी स्नॅक",
    "Handcrafted from premium dry fruits, seeds, and wood-pressed ghee without refined sugar—the perfect healthy snack for active lifestyles.": "रिफाइंड साखरेचा वापर न करता प्रीमियम सुका मेवा, बिया आणि लाकडी घाण्याच्या तुपापासून बनवलेले - सक्रिय जीवनशैलीसाठी योग्य निरोगी स्नॅक.",
    "Dr. Ananya Sharma": "डॉ. अनन्या शर्मा",
    "Ayurvedic Practitioner & Wellness Lead": "आयुर्वेदिक तज्ज्ञ आणि वेलनेस लीड",
    "Chef Rohan Deshmukh": "शेफ रोहन देशमुख",
    "Nutrition & Culinary Lead": "पोषण आणि पाककला प्रमुख",
    "Vaidya Suresh Patil": "वैद्य सुरेश पाटील",
    "Ayurvedic Doctor": "आयुर्वेदिक डॉक्टर",
    "Team Yogyahar": "टीम योग्याहार",
    "Wellness & Nutrition Team": "वेलनेस आणि न्यूट्रिशन टीम",
    "4 min read": "४ मिनिटे वाचन",
    "5 min read": "५ मिनिटे वाचन",
    "6 min read": "६ मिनिटे वाचन",
    "Read Full Article": "पूर्ण लेख वाचा",
    "Table of Contents": "अनुक्रमणिका",
    "1. Introduction": "१. प्रस्तावना",
    "2. Core Health Benefits": "२. मुख्य आरोग्य फायदे",
    "3. Ayurvedic Recommendations": "३. आयुर्वेदिक शिफारसी",
    "4. Routine Incorporation": "४. दिनचर्येत समाविष्ट करणे",
    "1. Satiety & Energy": "१. ऊर्जा आणि तृप्ती",
    "2. The Salad Blueprint": "२. सलाड आराखडा",
    "3. Smart Dressings": "३. स्मार्ट ड्रेसिंग",
    "1. Agni Principles": "१. अग्नी तत्त्वे",
    "2. The 5 Daily Habits": "२. ५ दैनिक सवयी",
    "3. Healthy Routine Planning": "३. निरोगी दिनचर्या नियोजन",
    "1. Midday Fatigue": "१. दुपारचा थकवा",
    "2. Nutritional Profile": "२. पोषण मूल्य",
    "3. Delivery Information": "३. वितरण माहिती",
    "Enjoyed this article?": "हा लेख आवडला का?",
    "Subscribe to fresh cold-pressed juices and high-protein salad meals delivered daily in Nashik.": "नाशिकमध्ये दररोज ताजे कोल्ड-प्रेस्ड ज्यूस आणि हाय-प्रोटिन सलाड घरपोच मिळवण्यासाठी सबस्क्राइब करा.",
    "Explore Fresh Products": "ताजी उत्पादने पहा",
    "Want to try our custom Salads?": "आमचे सानुकूल सलाड वापरायचे आहेत का?",
    "Order our customized high-protein bowls packed with seeds, sprouts, and premium vegetables.": "बिया, मोड आलेले कडधान्य आणि प्रीमियम भाज्यांनी युक्त आमचे हाय-प्रोटिन बाऊल ऑर्डर करा.",
    "Order Salads Now": "आता सलाड ऑर्डर करा",
    "Get Ayurvedic Consultation": "आयुर्वेदिक सल्ला मिळवा",
    "Connect with our certified practitioners to understand your body constitution (Dosha) and diet map.": "तुमची शारीरिक प्रकृती (दोष) आणि डाएट चार्ट समजून घेण्यासाठी आमच्या प्रमाणित डॉक्टरांशी संपर्क साधा.",
    "Consult Now": "आता सल्ला घ्या",
    "Try Our Fresh Super Laddus!": "आमचे ताजे सुपर लाडू वापरून पहा!",
    "Handcrafted with premium dates, dry fruits, seeds, and local wood-pressed ghee.": "प्रीमियम खजूर, सुका मेवा, विविध बिया आणि लाकडी घाण्याच्या तुपापासून बनवलेले.",
    "Browse Laddus": "लाडू खरेदी करा",
    "FAQ": "नेहमी विचारले जाणारे प्रश्न (FAQ)",
    "Social Media": "सोशल मीडिया",
    "Follow Us": "आम्हाला फॉलो करा",
    "Frequently Asked Questions": "वारंवार विचारले जाणारे प्रश्न",
    "Our Vision": "आमचे ध्येय (व्हिजन)",
    "Our Mission": "आमचे उद्दिष्ट (मिशन)",
    "Explore Our Fresh Selections": "आमची ताजी उत्पादने एक्सप्लोर करा",
    "Fruit bowls, juices, and tropical picks – all in one place.": "फळबाऊल, ज्यूस आणि बरेच काही - सर्व एकाच ठिकाणी.",
    "Hide Filters": "फिल्टर लपवा",
    "Show Filters": "फिल्टर दाखवा",
    "results": "निकाल",
    "Filters": "फिल्टर्स",
    "(Refine search)": "(शोध अचूक करा)",
    "Availability": "उपलब्धता",
    "In stock": "स्टॉकमध्ये उपलब्ध",
    "Category": "वर्ग (कॅटेगरी)",
    "Diet Goal": "डाएट ध्येय",
    "All Diet Goals": "सर्व डाएट ध्येये",
    "Weight Loss": "वजन कमी करणे",
    "Detox": "डिटॉक्स",
    "Muscle Gain": "मसल गेन",
    "General Health": "सामान्य आरोग्य",
    "Delivery Slots": "डिलिव्हरी स्लॉट्स",
    "All Slots": "सर्व स्लॉट्स",
    "Morning (6-9 AM)": "सकाळी (६-९ AM)",
    "Evening (5-7 PM)": "संध्याकाळी (५-७ PM)",
    "Both Slots": "दोन्ही स्लॉट्स",
    "Need Help?": "मदत हवी आहे का?",
    "Questions about a product? Our team is happy to guide you.": "उत्पादनाबद्दल काही शंका? आमची टीम नक्की मार्गदर्शन करेल.",
    "Chat on WhatsApp": "व्हाट्सएपवर चॅट करा",
    "SHOWING": "दाखवत आहे",
    "OF": "पैकी",
    "RESULTS": "निकाल",
    "Default sorting": "डिफॉल्ट रचना",
    "Sort by price: low to high": "किंमत: कमी ते जास्त",
    "Sort by price: high to low": "किंमत: जास्त ते कमी",
    "Sort by name: A-Z": "नावानुसार: A-Z",
    "No products found matching filters.": "फिल्टरनुसार कोणतीही उत्पादने आढळली नाहीत.",
    "OUT OF STOCK": "स्टॉकमध्ये उपलब्ध नाही",
    "Upcoming": "लवकरच येत आहे",
    "Active": "सक्रिय",
    "In Stock": "स्टॉकमध्ये आहे",
    "Out of Stock": "स्टॉकमध्ये नाही",
    "Plans from ₹1,000": "₹१,००० पासून प्लॅन्स",
    "View Product": "उत्पादन पहा",
    "NEXT >": "पुढे >",
    "Trending now": "सध्या लोकप्रिय (ट्रेंडिंग)",
    "Our Offerings": "आमच्या सेवा",
    "📍 Serviceable in whole Nasik area!": "📍 संपूर्ण नाशिक भागात डिलिव्हरी उपलब्ध!",
    "Who Is This For?": "हे कोणासाठी आहे?",
    "Yogyahar is crafted for everyone looking to transform their relationship with food and embrace vitality.": "ज्यांना आहाराची योग्य सवय लावून आरोग्य सुधारायचे आहे अशा सर्वांसाठी योग्याहार उत्तम पर्याय आहे.",
    "Ready to Begin Your Healthy Lifestyle?": "तुमची निरोगी जीवनशैली सुरू करण्यास तयार आहात का?",
    "Choose Yogyahar and enjoy dietitian-curated, delicious salads delivered daily.": "योग्याहार निवडा आणि तज्ञांनी बनवलेले चविष्ट सलाड दररोज घरपोच मिळवा.",
    "Custom Inquiry": "विशेष शंका/चौकशी",
    "Delivered Fresh": "ताजे डिलिव्हरी",
    "At your doorstep": "थेट आपल्या दारावर",
    "Secure Payment": "सुरक्षित पेमेंट",
    "100% safe & secure": "१००% सुरक्षित व खात्रीशीर",
    "Subscription Plans": "सबस्क्रिप्शन प्लॅन्स",
    "Save more with plans": "प्लॅन्स घेतल्यास अधिक बचत",
    "100% Satisfaction": "१००% समाधान",
    "We care for you": "आम्ही तुमची काळजी घेतो",
    "Yogyahar AI Assistant": "योग्याहार AI सहाय्यक",
    "Online • Instant Health Answers": "ऑनलाइन • त्वरित आरोग्य सल्ला",
    "Reset Chat": "चॅट पूर्ववत करा",
    "Close Chat": "चॅट बंद करा",
    "Ask about diet, plans, juices...": "डाएट, प्लॅन्स, ज्यूसबाबत विचारा...",
    "Chat with AI": "AI सोबत चॅट करा",
    "Namaste! 🙏 Welcome to Yogyahar! I'm your AI Health Assistant. How can I help you with our fresh diet meals, fruit bowls, or subscription plans today?": "नमस्ते! 🙏 योग्याहारमध्ये आपले स्वागत आहे! मी आपला AI आरोग्य सहाय्यक आहे. मी आज तुम्हाला आमच्या ताज्या आहारातील जेवण, फळबाऊल किंवा सबस्क्रिप्शन प्लॅन्सबाबत कशी मदत करू?",
    "🥗 What subscription plans do you offer?": "🥗 तुम्ही कोणते सबस्क्रिप्शन प्लॅन्स ऑफर करता?",
    "🌿 Are your juices 100% natural?": "🌿 तुमचे ज्यूस १००% नैसर्गिक आहेत का?",
    "🚚 Do you deliver across Nashik?": "🚚 तुम्ही संपूर्ण नाशिकमध्ये डिलिव्हरी करता का?",
    "📞 How can I connect or place an order?": "📞 मी ऑर्डर कशी देऊ किंवा संपर्क कसा करू?",
    "What Customers Say": "आमचे ग्राहक काय म्हणतात",
    "What Experts Say": "तज्ज्ञ काय म्हणतात",
    "One-Day Trial": "एक-दिवसीय ट्रायल",
    "View Details": "तपशील पहा",
    "Made with natural, wholesome ingredients": "नैसर्गिक आणि सकस घटकांपासून बनवलेले",
    "Wood pressed & chemical free": "लाकडी घाण्याचे आणि केमिकल विरहित",
    "Morning Slot": "सकाळची वेळ",
    "Evening Slot": "संध्याकाळची वेळ",
    "6–9 AM": "६-९ AM",
    "5–7 PM": "५-७ PM",
    "Ingredients": "घटक (साहित्य)",
    "Advantages": "फायदे",
    "Precautions": "काळजी (खबरदारी)",
    "Not Suitable For": "यांच्यासाठी योग्य नाही",
    "100% Pure": "100% शुद्ध",
    "Cold Pressed": "कोल्ड प्रेस्ड",
    "Fresh Delivery": "ताजी डिलिव्हरी",
    "Diet Friendly": "आहार पूरक",
    "Still have a Question? Chat with Us": "अजूनही काही प्रश्न आहे का? आमच्याशी गप्पा मारा",
    "Quick Links": "त्वरित लिंक",
    "Juices": "ज्यूस",
    "Detox Water": "डिटॉक्स वॉटर",
    "Salads & Fruit Cuts": "सॅलड आणि फळ काप",
    "Super Laddu": "सुपर लाडू",
    "Cold Pressed Oil": "कोल्ड प्रेस्ड ऑइल",
    "You can connect directly on": "तुम्ही थेट या नंबरवर संपर्क साधू शकता",
    "We Deliver At": "आम्ही येथे डिलिव्हरी करतो",
    "Home": "घर",
    "School": "शाळा",
    "College": "कॉलेज",
    "Office": "ऑफिस",
    "Gym": "जिम",
    "Hospitals": "रुग्णालय",
    "Dr. Rupali Pade": "डॉ. रूपाली पाडे",
    "Rishikesh Sonawane": "ऋषिकेश सोनावणे",
    "Ujjwala Kiran Petkar": "उज्ज्वला किरण पेटकर",
    "Rahul Bhamre": "राहुल भामरे",
    "Fresh Carrots, Touch of Ginger, Lemon Juice": "ताजे गाजर, आले आणि लिंबाचा रस",
    "Ingredients List": "घटक सूची",
    "Fresh, healthy, 100% organic juice": "ताजे, निरोगी, १००% सेंद्रिय ज्यूस",
    "Product Status": "उत्पादनाची स्थिती",
    "Products Includes": "उत्पादनामध्ये समाविष्ट",
    "Available Quantities": "उपलब्ध प्रमाण",
    "Single Product": "एकच उत्पादन",
    "Combination of Multiple Products": "अनेक उत्पादनांचे संयोजन",
    "200 ml / 300 ml / 500 ml": "२०० मिली / ३०० मिली / ५०० मिली",
    "200 gm / 450 gm": "२०० ग्रॅम / ४५० ग्रॅम",
    "Important Precautions": "महत्त्वाची काळजी",
    "Infants under 1 year, or individuals with severe kidney conditions.": "१ वर्षाखालील लहान मुले किंवा किडनीचा गंभीर आजार असलेले लोक.",
    "Consult doctor if managing high potassium or kidney conditions.": "किडनीचा काही त्रास असल्यास किंवा पोटॅशियम जास्त असल्यास डॉक्टरांचा सल्ला घ्या.",
    "Regular": "नियमित",
    "Seasonal": "हंगामी",
    "Special": "विशेष",
    "Available throughout the year": "वर्षभर उपलब्ध",
    "Available during the season": "हंगामात उपलब्ध",
    "Available in particular months only": "केवळ विशिष्ट महिन्यांतच उपलब्ध"
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("yogyahar_lang") || "en";
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem("yogyahar_lang", lang);
  };

  const t = (text) => {
    if (!text || typeof text !== "string") return text;
    const normalized = text.trim().replace(/\s+/g, " ");
    if (language === "en") return text;
    const dictionary = translationDictionary[language];
    if (dictionary) {
      const trimmed = text.trim();
      if (dictionary[trimmed] !== undefined) {
        return dictionary[trimmed];
      }
      for (const [key, value] of Object.entries(dictionary)) {
        if (key.trim().replace(/\s+/g, " ") === normalized) {
          return value;
        }
      }
    }
    return text;
  };

  // Helper to translate deep object/array fields recursively
  const translateObject = (obj) => {
    if (!obj || language === "en") return obj;

    if (Array.isArray(obj)) {
      return obj.map((item) => translateObject(item));
    }

    if (typeof obj === "object") {
      const result = {};
      for (const [key, val] of Object.entries(obj)) {
        if (typeof val === "string") {
          result[key] = t(val);
        } else if (typeof val === "object" || Array.isArray(val)) {
          result[key] = translateObject(val);
        } else {
          result[key] = val;
        }
      }
      return result;
    }

    return obj;
  };

  // HTML-aware translation helper that handles paragraphs, list items, and headings separately
  const tHtml = (htmlContent) => {
    if (!htmlContent || typeof htmlContent !== "string") return htmlContent;
    if (language === "en") return htmlContent;

    // A simple regex parser to identify HTML tags vs text content blocks
    // This allows us to translate the text content inside tags like <h2>, <h3>, <p>, <li>, <strong>, etc.
    try {
      const parser = new DOMParser();
      const doc = parser.parseFromString(`<div>${htmlContent}</div>`, "text/html");
      const wrapper = doc.body.firstChild;

      const translateNode = (node) => {
        if (node.nodeType === Node.TEXT_NODE) {
          const text = node.textContent;
          if (text && text.trim().length > 0) {
            node.textContent = t(text);
          }
        } else if (node.nodeType === Node.ELEMENT_NODE) {
          // If the element has specific contents mapped directly (like whole list items, headers or text snippets)
          // we can check if it matches in the dictionary
          const outerText = node.innerHTML.trim();
          const translatedOuter = t(outerText);
          if (translatedOuter !== outerText) {
            node.innerHTML = translatedOuter;
          } else {
            // Otherwise, translate children recursively
            node.childNodes.forEach(translateNode);
          }
        }
      };

      wrapper.childNodes.forEach(translateNode);
      return wrapper.innerHTML;
    } catch (e) {
      // Fallback to simple t() translation if DOMParser is unavailable or fails
      return t(htmlContent);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, tHtml, translateObject }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
